### PR TITLE
Fix WP CLI not connecting to the WP database in our e2e tests

### PR DESCRIPTION
**Pull request by luisherranz**
**What**:

Trying to fix this problem with our e2e tests: 

```
Error: Error establishing a database connection.
     CypressError: `cy.task('installPlugin')` failed with the following error:
> Command failed with exit code 1: docker-compose run --rm wpcli wp plugin install code-snippets
  From Node.js Internals:
    Error: Command failed with exit code 1: docker-compose run --rm wpcli wp plugin install code-snippets
        at makeError (/home/runner/work/frontity/frontity/e2e/node_modules/execa/lib/error.js:59:11)
        at handlePromise (/home/runner/work/frontity/frontity/e2e/node_modules/execa/index.js:114:26)
        at processTicksAndRejections (internal/process/task_queues.js:97:5u)
```

**Why**:

Apparently it appeared yesterday.

**How**:

Not sure yet. Let's try different things.

**Tasks**:

- [x] Fix end to end tests

**Unrelated Tasks**

- [ ] Code
- [ ] TSDocs
- [ ] TypeScript
- [ ] Unit tests
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Update community discussions
- [ ] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Additional Comments**

### CODE REVIEW

**Comment by luisherranz** [comment]
There was a new version of the WP CLI 6 days ago (v2.4.0) so I thought maybe going back to the previous version (v2.3.0) would solve the problem but it didn't.

**Comment by luisherranz** [comment]
A day ago WP 5.7 was released. Let's try with WP 5.6 image.

**Comment by luisherranz** [comment]
Ok, the problem is with the new 5.7 image.

**Comment by luisherranz** [comment]
Ok, let's keep it fixed like this for a few days, see if they solve the problem with a new WP image.

Michal, feel free to approve and merge right away if you agree.

**Comment by luisherranz** [comment]
The names changed so I've removed the e2e `dev` branch requirements for now (https://github.com/frontity/frontity/settings/branches).

We'll add them back once this is fixed.

**Review by michalczaplinski — APPROVED** [review]
awesome, thanks Luis 👍

**Pull request merged**
