### PR TITLE
Version Packages

### PR DESCRIPTION
**Pull request by frontibotito**
This PR was opened by the [Changesets release](https://github.com/changesets/action) GitHub action. When you're ready to do a release, you can merge this and the packages will be published to npm automatically. If you're not ready to do a release yet, that's fine, whenever you add more changesets to master, this PR will be updated.

# Releases

### CODE REVIEW

**Comment by luisherranz** [comment]
@santosguillamot can you please wait for a moment while I try to find out what is failing with Firefox 70 (https://github.com/frontity/frontity/runs/2465539177)? Thanks!

**Review by luisherranz — CHANGES_REQUESTED** [review]
Blocked by https://github.com/frontity/frontity/runs/2465539177.

**Comment by SantosGuillamot** [comment]
> @SantosGuillamot can you please wait for a moment while I try to find out what is failing with Firefox 70 (https://github.com/frontity/frontity/runs/2465539177)?

Sure, I was taking a look as well.

**Comment by luisherranz** [comment]
Bug opened here: https://github.com/frontity/frontity/issues/809

David is going to take care of it.

**Comment by SantosGuillamot** [comment]
I'm gonna close this Pull Request because we need a new one with the latest changes.

**Pull request closed without merging**
