### PR TITLE
fix(frontity): allow dots on packages names

### LINKED ISSUE #128: Cannot create a new project with a `.` character
Is there a reason for the limitation of characters when creating a new project? When I try to run the following command: `npx frontity create frontity.local` I get the following error: `Error: The name of the package is not valid. Please enter a valid one (only letters and dashes).`

### PR DESCRIPTION
**Pull request by cbravobernal**
allow_dots

Fixes #128.

### CODE REVIEW

**Comment by luisherranz** [comment]
I've added failing tests for the requirements of both package.json name and Unix/Window file systems.

**Comment by cbravobernal** [comment]
I will update the code then in order to make them pass :-)

**Comment by luisherranz** [comment]
😍

You can add some positive tests if you want.

**Review by orballo — APPROVED** [review]
Excellent contribution @c4rl0sbr4v0 @cluny85! 👏👏👏

**Pull request merged**
