### PR TITLE
Expose function for unescaping content from the WP REST API and use it in our themes.

### LINKED ISSUE #268: Frontity shows `&amp;` when ampersand is used in a title
**_Bug report_**

- [X] I've searched for existing issues
- [X] I've checked documentation: https://docs.frontity.org
- [X] I've checked community forum: https://community.frontity.org

**Describe the expected behavior**

If I use an ampersand in one category of my WordPress, it should display the character `&` instead of `&amp;`.

**Describe the observed behavior**

Frontity is displaying `&amp;` in both twentytwenty-theme and mars-theme for the category `Business & Marketing`.

**twentytwenty-theme**
Screen Shot 2020-01-17 at 08 23 21

**mars-theme**
Screenshot from 2020-01-17 10-51-50

### PR DESCRIPTION
**Pull request by michalczaplinski**
#### Description of what you did:

- [x] Update the implementation of `decode`
- [x] Expose the function in the `frontity` package
- [x] Use it in the 2020 theme
- [ ] ~Use it in the mars theme~ not necessary as far as I can tell.

#### My PR is a:

- 🐞 Bug fix
- 🚀 New feature

#### Is the PR ready to be merged?

- 🚧 Work in progress

### CODE REVIEW

**Comment by michalczaplinski** [comment]
@luisherranz It's not clear to me just looking at the code how to expose the `decode` correctly for both the server and the client. Right now, I just exposed the client-side implementation and surprisingly it just works, but I thought that it would fail on the server.

**Comment by luisherranz** [comment]
This was closed because I deleted the `beta` branch, sorry. I'm going to reopen it.

**Comment by luisherranz** [comment]
It looks like I can't :(

I'll open a new PR, sorry about this.

**Comment by luisherranz** [comment]
There you go: https://github.com/frontity/frontity/pull/302

**Pull request closed without merging**
