### PR TITLE
Updates image links

### PR DESCRIPTION
**Pull request by mburridge**
**What**:

Updates image links in theme README.md files to point to new location for images at frontity.org

**Why**:

Image files moved to new location due to GitBook updates breaking the links.

**How**:

**Tasks**:

- [x] Update starter themes
- [x] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Unrelated Tasks**

- [ ] Code
- [ ] TSDocs
- [ ] TypeScript
- [ ] Unit tests
- [ ] End to end tests
- [ ] TypeScript tests
- [ ] Update other packages
- [ ] Update community discussions

**Additional Comments**

### CODE REVIEW

**Review by luisherranz — DISMISSED** [review]
@mburridge, could you please resolve the conflicts? I'm not sure which of the images is the correct one.

**Review by cristianbote — APPROVED** [review]

**Comment by mburridge** [comment]
> @mburridge, could you please resolve the conflicts? I'm not sure which of the images is the correct one.

Resolved.

**Review by DAreRodz — COMMENTED** [review]
Hey, I was passing by and ― were this changes done in a different PR and merged into `dev` already? The only file listed in "Files changed" is the changeset. :eyes:

cc: @mburridge @luisherranz

**Comment by luisherranz** [comment]
It seems so, yes. Maybe these two from @juanmaguitar: https://github.com/frontity/frontity/commit/12eb5cc4a98534a0b65ce2e316693c94722695e8 https://github.com/frontity/frontity/commit/27eb4e0847b002ff26845f5e3f231dc43a637f88.

@juanmaguitar can you confirm this? And if so, and if the changes were the ones of your commits, merge this PR?

**Comment by juanmaguitar** [comment]
> @juanmaguitar can you confirm this? And if so, and if the changes were the ones of your commits, merge this PR?

Yes, I confirm I did these commits directly to `dev` and that these are the right links for the images

https://github.com/frontity/frontity/commit/12eb5cc4a98534a0b65ce2e316693c94722695e8 https://github.com/frontity/frontity/commit/27eb4e0847b002ff26845f5e3f231dc43a637f88.

**Comment by luisherranz** [comment]
Ok, thanks Juanma. Merging this then.

**Pull request merged**
