### PR TITLE
Fixes archive not being fetched when post type is loaded from SSR

### PR DESCRIPTION
**Pull request by orballo**
**What**:

Fixes a bug where the archive is not requested if a post type is loaded from SSR.

**Why**:

It was a bug.

**How**:

Removed the condition where the link must belong to an archive to be requested. This is wrong because before requesting it that value of `data.isArchive` will always evaluate as false.

**Tasks**:

- [x] Code
- [x] Unit tests
- [x] Changeset

**Unrelated Tasks**
-  TSDocs
-  TypeScript
-  End to end tests
-  TypeScript tests
-  Update starter themes
-  Update other packages
-  Link to PR in [Documentation](https://github.com/frontity/gitbook-docs/)
-  Community discussions

**Additional Comments**

### CODE REVIEW

**Comment by michalczaplinski** [comment]
Assigned it to me because I'm the supporter this week.

**Review by michalczaplinski — COMMENTED** [review]
I think I don't have all the context to review this efficiently - I think @luisherranz should have a look 🙂

**Review by luisherranz — APPROVED** [review]
Thanks @orballo and sorry for the delay.

**Comment by luisherranz** [comment]
I have published a new beta version with this change: `@frontity/hooks@2.1.0-infinite-scroll-beta.1`.

**Pull request merged**
