### PR TITLE
chore(types): moves types from 'index.ts' to 'types.ts'

### PR DESCRIPTION
**Pull request by orballo**
#### Description of what you did:

Solves https://github.com/frontity/frontity/issues/121

I didn't find any dependency between packages regarding the changes, I mean somewhere we were using the types and that now would fail, but if you think of anything let me know and I'll fix it.

#### My PR is a:

- [ ] 🐞 Bug fix
- [ ] 🚀 New feature
- [x] 🔝 Improvement

#### Main update on the:

- [ ] Documentation
- [x] Framework

#### Is the PR ready to be merged?

- [x] Yes!
- [ ] Work in progress

### CODE REVIEW

**Review by luisherranz — APPROVED** [review]
LGTM @orballo! :)

**Comment by luisherranz** [comment]
I'm not sure why Travis is failing:
```
src/scripts.ts(3,15): error TS2307: Cannot find module '@frontity/core'.
```

The dependencies of `frontity` look good to me.

I'm going to restart the builds.

**Comment by luisherranz** [comment]
I'm not able to break it locally.

**Comment by orballo** [comment]
I know what's going on. Will work on it later today. The thing is after moving `types.ts` out of the `src` folder in `@frontity/core` the directory structure changed inside the `dist` folder, so we need to update `package.json` accordingly.

**Comment by orballo** [comment]
But I'm not actually sure we want to move the types in `@frontity/file-settings` and `@frontity/core`. I did it to have a similar structure between packages, but their types are not going to be used by developers, right? Let me know what you think about this.

**Comment by luisherranz** [comment]
Yes, any type that should be used by developers would have to moved to `@frontity/types` so no problem about that.

**Comment by luisherranz** [comment]
Awesome :)

**Pull request merged**
