### PR TITLE
Add TSDocs for the types of wp-source

### PR DESCRIPTION
**Pull request by luisherranz**
**What**:

I wanted to create some real TSDocs so the documentation team can have a better picture of how everything is going to look like.

**Why**:

Because we are working on an API template for the docs in this thread: https://community.frontity.org/t/code-documentation-workflow/1633/15

**Tasks**:

- [x] TSDocs for actions
- [x] TSDocs for state
- [x] TSDocs for libraries

**Unrelated Tasks**

- Code
- TypeScript
- Unit tests
- End to end tests
- TypeScript tests
- Update starter themes
- Update other packages
- Link to PR in [Documentation](https://github.com/frontity/gitbook-docs/wiki/Code-Releases)
- Community discussions
- Changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Additional Comments**

The goal of this PR is to agree in a way to document the `types.ts` files of our packages.

@darerodz @michalczaplinski  I'd love to know your opinion. Feel free to go ahead and add additional commits to this PR.

### CODE REVIEW

**Comment by michalczaplinski** [comment]
Looks great! 👍 I've just reworded the tsdoc a little bit but the form is great.

**Comment by DAreRodz** [comment]
I think it's great! :raised_hands: 

My only concern is about the `@example` tag. I saw it used to show examples about how to use a function, but not for parameters.

FYI, I found a converstation in the TSDoc repository where it's proposed a "normalized" doc comment format: https://github.com/microsoft/tsdoc/issues/13#issuecomment-563489557 (it's also mentioned there an [inventory of standard tags](https://github.com/microsoft/tsdoc/blob/master/tsdoc/src/details/StandardTags.ts)). Maybe it is useful to check that as well.

**Comment by luisherranz** [comment]
I'll try to finish this (to not throw the work away) once https://github.com/frontity/frontity/pull/500 is merged.

**Comment by SantosGuillamot** [comment]
>I'll try to finish this (to not throw the work away) once #500 is merged.

This one has already been merged :slightly_smiling_face:

**Comment by luisherranz** [comment]
There is a mistake in the docs right now: we show `route` instead of `link` in handlers. I'll open an issue.

Other than that, I'd love to hear your feedback, but please do so in the community thread where we are talking about this to keep the conversation in context: https://community.frontity.org/t/code-documentation-workflow/1633/23

**Comment by luisherranz** [comment]
> There is a mistake in the docs right now: we show route instead of link in handlers. I'll open an issue.

Done in https://github.com/frontity/docs/pull/141/commits/16e81a482e23b28aec36485c58195e0df94328b5

**Review by michalczaplinski — APPROVED** [review]
LGTM! 👍 

I think this is worth the effort and when it works together with the hover tooltips in VSCode should make using frontity much easier.

I've added some very small changes to wording and some of the examples

**Comment by luisherranz** [comment]
Thanks @michalczaplinski

**Pull request merged**
