### PR TITLE
Pin node-fetch version temporarily

### LINKED ISSUE #868: Can't import the named export 'URL' from non EcmaScript module (only default export is available)
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**
Should have installed all the dependencies 

**Observed behavior**
Frontity fails to install upon running `npx frontitty dev`

**Steps involved to reproduce the problem**
1. Use `npx frontity create my-app`
2. `cd my-app`
3. `npx frontity dev`

`ERROR in ./node_modules/node-fetch/lib/index.mjs 1157:18-21
    Can't import the named export 'URL' from non EcmaScript module (only default export is available)
     @ ./node_modules/frontity/dist/src/index.js
     @ ./node_modules/@frontity/tiny-router/src/actions.ts
     @ ./node_modules/@frontity/tiny-router/src/index.ts
     @ ./build/bundling/entry-points/server.ts`

**Info about your system**

## System:
 - OS: Windows 10 10.0.19043
 - CPU: (8) x64 Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz
 - Memory: 5.47 GB / 15.85 GB
## Binaries:
 - Node: 14.17.6 - C:\Program Files\nodejs\node.EXE
 - npm: 7.5.2 - C:\Program Files\nodejs\npm.CMD
## Browsers:
 - Chrome: Not Found
 - Edge: Spartan (44.19041.1023.0), Chromium (93.0.961.52)
 - Internet Explorer: 11.0.19041.1202
## npmPackages:
 - @frontity/core: ^1.14.3 => 1.14.3
 - @frontity/html2react: ^1.7.0 => 1.7.0
 - @frontity/mars-theme: ./packages/mars-theme => 1.6.1
 - @frontity/tiny-router: ^1.4.4 => 1.4.4
 - @frontity/wp-source: ^1.11.5 => 1.11.5
 - frontity: ^1.17.0 => 1.17.0
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found

**Possible solution**

### PR DESCRIPTION
**Pull request by luisherranz**
**What**:

Temporarily pin the version of `node-fetch` to 2.6.2. Fixes #868.

**Why**:

Because `node-fetch` introduced a problem with an import in the 2.6.3 version that is breaking Frontity.

**How**:

By removing the `^` of the version number for now.

**Tasks**:

- [x] Package.json's
- [x] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Unrelated Tasks**

- [ ] Code
- [ ] TSDocs
- [ ] TypeScript
- [ ] Unit tests
- [ ] End to end tests
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Update community discussions

**Additional Comments**

Thanks to @robrecord for the catch 🙂

### CODE REVIEW

**Comment by robrecord** [comment]
You're welcome! And thanks for the fix.

By the way, `node-fetch` just [created a patch for this](https://github.com/node-fetch/node-fetch/pull/1303) which is waiting for confirmation as they cannot reproduce. I am not yet sure how I can validate this patch with `frontity` but I will try. 

Once confirmed, they can publish it and we can then release the constraint on this version.

I will confirm on my end if I can; if you have a chance to confirm also that would be very helpful.

**Comment by luisherranz** [comment]
Thanks @robrecord. If tests pass I think we can merge and release this so we don't depend on when `node-fetch` merges and releases their fix.

**Review by michalczaplinski — APPROVED** [review]
LGTM 👍

**Comment by luisherranz** [comment]
Thanks Michal!

**Comment by sainer** [comment]
Instructions for for less experienced users.

1. Find in your project node_modules folder package named frontity.
2. In frontity folder there is package.json file. Edit it.
3. Find in dependencies node-fetch package. Change its value to  "2.6.2" (without ^ sign). Save file.
4. Run npm update in your root project folder

**Pull request merged**
