### PR TITLE
WpSource: Fix `state.source.api` for WP.com sites

### LINKED ISSUE #622: wordpress.com sites not working with `state.source.url` [5pt]
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

Using a wordpress.com address in `state.source.url` in `frontity.settings.js` should result in the data being fetched and the site behaving normally. 

**Observed behavior**

A 404 not found error occurs.

**Steps involved to reproduce the problem**

Straight after setting up a new site with `npx frontity create` change the `state.source.url` setting in `frontity.settings.js` to a URL pointing to a wordpress.com site.

**Info about your system**

**Possible solution**

In line 77 of `packages/wp-source/src/state.ts` it looks like the full `state.source.url` is being appended to the string `https://public-api.wordpress.com/wp/v2/sites/`, including the `https://` prefix, resulting in a URL something like:

```
https://public-api.wordpress.com/wp/v2/sites/https://my-site.wordpress.com
```

The `https://` prefix needs to be stripped out before `state.source.url` is appended.

### PR DESCRIPTION
**Pull request by DAreRodz**
**What**:

Fix `state.source.api` for users with a free WordPress.com site (i.e. https://mysite.wordpress.com).

Closes #622

**Why**:

The URL for the REST API is not generated correctly if `state.source.url` is set to a URL pointing to a free WordPress.com site, and every request to it fails.

**How**:

Using the fix proposed by @mburridge here: https://github.com/frontity/frontity/issues/622#issuecomment-732139397

**Tasks**:

- [x] Code
- [x] Unit tests
- [x] Update other packages
- [x] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Unrelated Tasks**

- [ ] TSDocs
- [ ] TypeScript
- [ ] End to end tests
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Open an issue for this feature in the [docs repo](https://github.com/frontity/docs/wiki/Code-Releases)
- [ ] Update community discussions

**Additional Comments**

### CODE REVIEW

**Comment by DAreRodz** [comment]
I just added the code proposed by @mburridge and updated the unit tests.

Is there anything missing that I'm not aware of? 👀

**Comment by DAreRodz** [comment]
> Is there anything missing that I'm not aware of?

Oh, sure there is! :sweat_smile:

I completely overlooked the discussion in the [community](https://community.frontity.org/t/make-the-backend-url-a-global-setting/2381/41)... :sweat_smile::sweat_smile::sweat_smile:

**Comment by DAreRodz** [comment]
@luisherranz, just in case you want to finish this next week, there are some tests failing in the `@frontity/head-tags` package and probably someone else, but all the work in `@frontity/wp-source` is done. :+1:

**Comment by luisherranz** [comment]
Ok, thanks @david. I have other things to focus on first, but I finish those I will continue with this 🙂

**Comment by DAreRodz** [comment]
Uh, I don't understand but, after a merge without any code changes, the unit tests are not passing anymore. :thinking:

**Comment by luisherranz** [comment]
@michalczaplinski could you please do this review? Thanks!! 🙂

**Review by michalczaplinski — COMMENTED** [review]
LGTM, nice work @DAreRodz! :) 

I just only have one comment, which is that I think sprinkling some comments on github explaining why a particular change was made and how it relates to some other piece of code in another file would make it a bit easier to review in the future :) 

In this particular PR for example, there are some changes in the head-tags and yoast packages which are not immediately obvious why they had to be made and the `transformLink` util is refactored in a way that is not obvious either.

Not a big deal, but let's try to communicate that in the future.

**Review by michalczaplinski — APPROVED** [review]

**Comment by DAreRodz** [comment]
> Not a big deal, but let's try to communicate that in the future.

You are completely right, @michalczaplinski, sorry about that!

I should have explained in the description of the PR why those changes were included.

`transformLink` is the function used by `@frontity/wp-source` to adapt the `link` property of each entity so it points to the Frontity server. It was using the `state.source.api` property to get the WP URL, instead of using `state.source.url` directly - that's why I refactored that.

Something similar happened with the `getWpUrl()` function used by `@frontity/head-tags` and `@frontity/yoast`.

**Pull request merged**
