### PR TITLE
Update SmartAdserver e2e tests to use our ad units

### LINKED ISSUE #612: Change ad ids for the SmartAds e2e tests to the use official sandbox [3pt]
When we developed the `@frontity/smart-adserver` package, we used a private account for the e2e tests. We asked the SmartAds team for a sandbox account and they have provided the information needed, so we should change them. This is what they shared:

```
<script type="application/javascript" src="https://ced.sascdn.com/tag/256/smart.js" async></script>
<div id="sas_8025"></div>
<script type="application/javascript">
    var sas = sas || {};
    sas.cmd = sas.cmd || [];
    sas.cmd.push(
        function () {
            sas.call(
                { siteId: 383739, pageId: 1326721, formatId: 8025, tagId: "sas_8025" },
                { networkId: 256, domain: "https://www3.smartadserver.com" /*, onNoad: function() {} */ }
            );
        }
    );
</script>
Los formatos tienen este ID:
728x90: Image -> 6467
300x100: Html5 -> 8025
300x250: Image -> 19809
300x600: Html5 -> 58374
```

### PR DESCRIPTION
**Pull request by DAreRodz**
**What**:

Closes #612 

**Why**:

To stop using ad units from a third-party account.

**How**:

Replacing the old ad units with the new ones and updating the spec file.

**Tasks**:

- [x] End to end tests

**Unrelated Tasks**

- [ ] Code
- [ ] TSDocs
- [ ] TypeScript
- [ ] Unit tests
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Open an issue for this feature in the [docs repo](https://github.com/frontity/docs/wiki/Code-Releases)
- [ ] Update community discussions
- [ ] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Additional Comments**

No changeset needed in this case.

### CODE REVIEW

**Comment by luisherranz** [comment]
@darerodz for the emails with SmartAds I deduced that this is not ready for review yet, so I have removed myself. Is that right?

**Comment by DAreRodz** [comment]
Not really, using a custom `tagId` is something that the SmartAdserver library doesn't allow for `iframe` calls. I'll just leave it as it is right now.

**Review by michalczaplinski — APPROVED** [review]
LGTM, although I don't understand this: I thought that the new format IDs did not work, but the tests are passing so I assume that there are working after all? @DAreRodz

**Comment by DAreRodz** [comment]
@michalczaplinski, the ads were not shown but that was fixed by the SmartAdserver team. They are working now as expected.

The only thing is with the `iframe` call that doesn't work with a custom `tagId`, but that's a problem in the SmartAdserver library.

**Pull request merged**
