### PR TITLE
Add support for images in webpack (png, jpg, gif and svg)

### PR DESCRIPTION
**Pull request by luisherranz**

### CODE REVIEW

**Review by orballo — APPROVED** [review]

**Comment by millerf** [comment]
Hi,

I am still having trouble using SVG in production.
using `frontity dev` works fine, but after `frontity build`, `frontity serve` do not display the SVGs...
I am using [ReactSVG](https://www.npmjs.com/package/react-svg). The images are in `build/static/images`  but they are not displayed, neither is there any error or requests to retrieve them... Any idea? I'll create a new issue for it...

**Comment by luisherranz** [comment]
Could you please open an issue with the description of the problem and a repository that reproduces the issue? For the repository please start with `npx frontity create` and mars-theme and add the minimum amount of code to get to the problem. Thanks! 🙂

**Comment by millerf** [comment]
I fixed it. It wasn't frontity-related. Thanks anyway!

**Comment by luisherranz** [comment]
Awesome. Thanks for letting us know @millerf  🙂

**Pull request merged**
