### PR TITLE
HTML2React: update type declarations

### LINKED ISSUE #352: Improve types for Html2React processors
# Description

Right now, using TypeScript when declarating a processor for the Html2React package has some problems (see discussion here: https://github.com/frontity/frontity/commit/f7f2e6eab85889465764ae70d1fe73364db5b0ad#r37684196):

- `node` type is not inferred correctly and a type guard is needed to consider it of type `Element`.
- `parent` and `children` nodes cannot be typed with the current implementation. Also, the default props type of this nodes is `unknown` which is not a good default type.

# Possible solution

To solve this issue, the idea is to pass not only the types of the props but the type of the element as well and its `parent` and `children` attributes. Some of this attributes could be optional and the final types would be the passed types merged with a default type.

E.g.

```ts
type LazyImgWrapper = {
  type: "element";
  component: "figure";
  children: [LazyImg];
}

type LazyImg = {
  type: "element";
  component: "img";
  props: { "data-src": string };
  parent: LazyImgWrapper;
};

const myProcessor: Processor<LazyImg> = {
  test: ({ node }) => { },
  processor: ({ node }) => {
    node.props["data-src"] // <- this should be of type `string`
    node.parent.component // <- this should be of type `"figure"`
  }
};
```

### PR DESCRIPTION
**Pull request by iamuchejude**
**What**:

- Improve Processor type.
- Update html2react processors.

**Why**:

Problem with declaring types for HTML2React Processor. 

**Relevant tasks**:

- [x] TypeScript
- [x] TypeScript tests
- [x] Refactoring of HTML2React processors
- [x] Changeset
- [ ] ~Refactoring of frontity.org processors~ To do in a different issue (https://github.com/frontity/frontity.org/issues/79).

**Non relevant tasks**:
- [ ] ~Code~
- [ ] ~Documentation~
- [ ] ~Unit tests~
- [ ] ~End to end tests~
- [ ] ~Starter Themes~
- [ ] ~Community discussions~

### CODE REVIEW

**Comment by luisherranz** [comment]
I've added a new task called refactoring for the refactoring of the types of the processors we have so far.

**Comment by luisherranz** [comment]
I have added a new task: TypeScript tests.

**Comment by luisherranz** [comment]
Please guys, remember to update the tasks, assign this to yourself and link to the original issue.

**Comment by DAreRodz** [comment]
We are having a problem with TypeScript: the types are working fine when you define a processor but they're not working in the internal functions that we are using to render the `Html2React` component.

I'm going to take a look at the code to see how it could be solved.

**Comment by luisherranz** [comment]
@DAreRodz can you please add that info to the issue instead? https://github.com/frontity/frontity/issues/352

**Comment by DAreRodz** [comment]
I thought this is the place to have that conversation... Nevermind, @iamuchejude already post the same info in the issue: https://github.com/frontity/frontity/issues/352#issuecomment-613982329

**Comment by DAreRodz** [comment]
Ready to review!

@iamuchejude I cannot assign you as a reviewer because you started the PR, but you could check the code as well. :smile:

**Review by luisherranz — APPROVED** [review]
Excellent. Thanks @DAreRodz and @iamuchejude for your work here 🙂 

I did a few extra things:
- I moved `expectType` to `frontity/types/helpers` to avoid maintaining duplicate code.
- I added a test for custom elements in children.
- I deleted unnecessary `node.type === "element"` checks in the `test` functions.

I did a couple of things not related to this, sorry, I should've done a new PR:
- I got rid of `parse` export in `libraries.html2react`.
- I moved `decode` to `utils` inside `frontity`.

Feel free to merge guys!

**Comment by luisherranz** [comment]
@iamuchejude please go through the code and ask anything you don't understand 🙂

**Pull request merged**
