### PR TITLE
Right way of handling search results (TwentyTwenty theme)

### PR DESCRIPTION
**Pull request by juanmaguitar**
**What**:

Updated way of handling search results pages with Frontity

**Why**:

So the user have a better reference for this

**How**:

Updating proper components in the theme

**Tasks**:

- [x] Code
- [x] Update starter themes
- [x] Documentation
- [x] Community discussions
- [x] Changeset

**Unrelated**:

- ~Update other packages~
- ~TypeScript~
- ~Unit tests~
- ~End to end tests~
- ~TypeScript tests~

**Related info**:
https://github.com/frontity/gitbook-docs/pull/45
https://community.frontity.org/t/search-links-and-pagination-in-data-objects-of-wp-source/1230/7

### CODE REVIEW

**Comment by luisherranz** [comment]
@juanmaguitar would you mind adding a changeset? https://docs.frontity.org/contributing/code-contribution-guide#changelogs

Thanks!

**Comment by juanmaguitar** [comment]
Changeset added

**Review by SantosGuillamot — APPROVED** [review]
It seems to be working great! :slightly_smiling_face: Thanks Juanma!

**Comment by DAreRodz** [comment]
Hey, I've just saw that this PR was ready to be merged a couple of days ago. I'm going to merge it.

**Pull request merged**
