### PR TITLE
Add eslint-plugin-tsdoc and basic configuration

### PR DESCRIPTION
**Pull request by luisherranz**
**What**:

Add the `eslint-plugin-tsdoc` to our eslint configuration.

**Why**:

To have some linting regarding some questions we had, like if we should use `@return` or `@retuns`, `@default` or `@defaultValue` and so on.

**How**:

By installing the package in the root and adding it as a plugin in our `eslintrc` file.

**Tasks**:

- [x] eslint-plugin-tsdoc
- [x] eslint-plugin-jsdoc
- [x] GitHub action

**Unrelated Tasks**

- TSDocs
- TypeScript
- Unit tests
- End to end tests
- TypeScript tests
- Update starter themes
- Update other packages
- Link to PR in [Documentation](https://github.com/frontity/gitbook-docs/wiki/Code-Releases)
- Community discussions
- Changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

### CODE REVIEW

**Comment by luisherranz** [comment]
After a quick look at `eslint-plugin-jsdoc` I think we can combine both. I'll update this PR with it.

**Comment by luisherranz** [comment]
@DAreRodz @michalczaplinski could you please check this out, play a bit with different files and let me know what you see?

**Comment by luisherranz** [comment]
@namespaces don't work by the way. The rest it does, I think.

**Comment by luisherranz** [comment]
Well, I think this is ready to merge, although I'm going to leave the eslint errors so you can take a look at how they look here in GitHub. I'll fix the file once you approve it.

I guess the js-doc config is not going to be perfect just yet, we'll need to adjust it once we use it, but I think it's good enough to get us started.

@darerodz @michalczaplinski I assign you both as reviewers so we have a consensus on this.

@santosguillamot, I won't merge this. Feel free to merge it whenever you deem appropriate.

**Comment by SantosGuillamot** [comment]
Great, thanks @luisherranz ! I think we can merge it whenever is ready. I would try to avoid to delay anything that has already been implemented. Apart from that, all the upcoming features are new packages, where we were planning to add the docs anyway, so it's safer to have this.

**Review by DAreRodz — APPROVED** [review]
Sorry for being late here. I was playing around and everything seems fine. :+1: 

Approved!

**Comment by luisherranz** [comment]
Thanks @darerodz. I'm going to wait on @michalczaplinski on this one too.

**Review by michalczaplinski — APPROVED** [review]
I've checked it out. Looks great, thanks Luis. 🙂 

Let's see if we need to adjust it more with time then

**Comment by luisherranz** [comment]
@santosguillamot feel free to merge whenever you want. Be aware that at the moment we merge this, other open PRs will need to be updated.

**Pull request merged**
