### PR TITLE
Google ad manager readme

### PR DESCRIPTION
**Pull request by mburridge**
**What**:

Adds content to `packages/google-ad-manager/README.md`.

**Why**:

Substantial content was missing.

**How**:

I typed it! ¯\_(ツ)_/¯

**Tasks**:

- [x] Update README files

**Unrelated Tasks**

- [ ] Code
- [ ] TSDocs
- [ ] TypeScript
- [ ] Unit tests
- [ ] End to end tests
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Update community discussions
- [ ] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Additional Comments**

### CODE REVIEW

**Review by juanmaguitar — CHANGES_REQUESTED** [review]
I think we should apply here the same logic we commented about distributing the information between the README and the DOCS:
- README.md → brief introduction of the package, some quick start notes and link to the proper page in the docs
- DOCS → Detailed explanation of the package

**Comment by mburridge** [comment]
> I think we should apply here the same logic we commented about distributing the information between the README and the DOCS:
> 
> * README.md → brief introduction of the package, some quick start notes and link to the proper page in the docs
> * DOCS → Detailed explanation of the package

Done, please take another look

**Review by DAreRodz — APPROVED** [review]
Just great! :raised_hands:

**Review by juanmaguitar — APPROVED** [review]

**Comment by cristianbote** [comment]
@mburridge @juanmaguitar @DAreRodz I believe we are good in here, right? Can I merge this one?

**Comment by mburridge** [comment]
@cristianbote Yup, go ahead. 👍

**Pull request merged**
