### PR TITLE
Remove verbose regexps

### PR DESCRIPTION
**Pull request by DAreRodz**
**What**:

Get rid of the internal util `verboseRegExp`.

**Why**:

Verbose RegExps were leaking into the bundle without being minified.

Screenshot 2021-05-14 at 09 37 23

**How**:

Replacing verbose RegExps by regular regexps + TSDocs.

**Tasks**:

- [x] Code
- [x] TSDocs
- [x] Unit tests
- [x] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Unrelated Tasks**

- [ ] TypeScript
- [ ] End to end tests
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Update community discussions

**Additional Comments**

I used TSDocs because I found them useful to preserve identation in comments (yeah, I had some trouble with the [Rewrap](https://marketplace.visualstudio.com/items?itemName=stkb.rewrap) extension :sweat_smile:).

### CODE REVIEW

**Comment by DAreRodz** [comment]
Poor `verboseRegExp` ― you weren't such a good idea in the end. :shrug:

**Comment by luisherranz** [comment]
> Poor verboseRegExp ― you weren't such a good idea in the end. 🤷

Today is a sad day 😔

**Comment by cristianbote** [comment]
Looks fine from my end @DAreRodz, but I think @michalczaplinski it would be the best to review this, since he's the one I think who introduce the verbose regexp, no?

**Review by michalczaplinski — APPROVED** [review]
Yeah, looks good to me, bye bye verboseRegexp! 

Good catch @cristianbote, by the way.

**Review by cristianbote — APPROVED** [review]

**Comment by luisherranz** [comment]
> since he's the one I think who introduce the verbose regexp, no?

I think that was David 🙂

**Pull request merged**
