### PR TITLE
Purge expired artifacts

### PR DESCRIPTION
**Pull request by luisherranz**
**What**:

Purge the expired artifacts.

**Why**:

Because the Eslint GH action is failing a lot lately and it seems like expired artifacts can be the cause, acording to this issue: https://github.com/bradennapier/eslint-plus-action/issues/45.

**How**:

By adding a previous step in the Eslint GH action that purges the expired artifacts before eslint runs.

**Tasks**:

- [x] GH action

**Unrelated Tasks**

- [ ] TSDocs
- [ ] TypeScript
- [ ] Unit tests
- [ ] End to end tests
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Update community discussions
- [ ] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Additional Comments**

### CODE REVIEW

**Comment by luisherranz** [comment]
I keep hitting the rate limit. I'll wait a while and retrigger the purge action again.

**Comment by luisherranz** [comment]
It seems like there are many artifacts, so maybe it'd be better to merge this and let it run each 15 minutes until they are all gone.

@santosguillamot, would mind taking a look and approving this PR? Thanks.

**Comment by SantosGuillamot** [comment]
I've seen that in the GitHub action you added, [LKP-RnD/purge-expired-artifacts-action@v4](https://github.com/LKP-RnD/purge-expired-artifacts-action), they mention as a [common issue](https://github.com/LKP-RnD/purge-expired-artifacts-action#common-issues) this:

_"If you have thousands of expired artifacts the action won't be able to delete everything in one go as githubs API has a rate limit. However, if you run it on a schedule as in the example every other hour you will eventually come to a point where the script will have cleared most unused artifacts and this will no longer cause problems."_

Checking [the repo in GitHub artifacts API](https://api.github.com/repos/frontity/frontity/actions/artifacts), it seems that there are 4583. So I guess this could be the problem.

I guess we have to remove the artifacts manually or, as they suggest, implement a CRON workflow triggering the action you added.

**Comment by luisherranz** [comment]
> I guess we have to remove the artifacts manually or, as they suggest, implement a CRON workflow triggering the action you added.

The CRON is already set up for this action. That is the reason I thought we may just merge this and let it fun each 15 minutes until they are all gone 🙂

**Comment by SantosGuillamot** [comment]
> It seems like there are many artifacts, so maybe it'd be better to merge this and let it run each 15 minutes until they are all gone.

Oh, I was just writing my answer 🙂 . Triggering it removed like 300 artifacts, so we'll need it to run a few times until all of them are deleted.

> @SantosGuillamot, would mind taking a look and approving this PR? Thanks.

Sure, I was already on it. Approving it 👍

**Review by SantosGuillamot — APPROVED** [review]
LGTM 👍

**Comment by luisherranz** [comment]
Haha, ok, we were talking about the same at the same time 😄

Thanks Mario, I'll merge it now and I'll keep an eye on the action runs after that.

**Comment by luisherranz** [comment]
BTW, these are the action run by the workflow each 15 min: https://github.com/frontity/frontity/actions/workflows/eslint.yml

**Comment by SantosGuillamot** [comment]
> BTW, these are the action run by the workflow each 15 min: https://github.com/frontity/frontity/actions/workflows/eslint.yml

I saw it in the changed files, thanks Luis 🙂 

Btw, I think I can trigger it manually until the artifacts are gone. There are 3884 left -> https://api.github.com/repos/frontity/frontity/actions/artifacts

**Comment by luisherranz** [comment]
578 now! https://api.github.com/repos/frontity/frontity/actions/artifacts 😄 👏

**Pull request merged**
