### PR TITLE
Fixes broken links in README files

### LINKED ISSUE #654: Broken links in package READMEs
In https://github.com/frontity/frontity/tree/dev/packages/frontity:

* More info on npx frontity create [here](https://docs.frontity.org/frontity-cli/create) – should probably lead to https://docs.frontity.org/frontity-cli/create-commands#create
* Have a look at the latest updates of this package in the [CHANGELOG](https://github.com/frontity/frontity/blob/dev/packages//CHANGELOG.md) – should probably be a relative one

Open Source Community section in many packages:
* Subscribe to our [newsletter](https://frontity.org/#newsletter) – the newsletter portion is below the fold for me, probably because of the twitter testimonials being lazy-loaded
* See our [Contributing](https://github.com/frontity/frontity/blob/dev/packages/contributing) section to find out how you can help develop Frontity, or improve this documentation.

### PR DESCRIPTION
**Pull request by mburridge**
**What**:

Fixing broken links in the README.md files in various packages. 

Adding or updating the 'Open Source Community' section of the README.md files in some packages.

**Why**:

Some links were broken (as reported in issue 654). Some README files had no content. Some README files had different versions of the 'Open Source Community' section 

**How**:

New newsletter page created.
Changed absolute URLs to relative URLs.
Added or updated content where necessary.

**Tasks**:

- [x] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)
- [x] Update README files

**Unrelated Tasks**

- [ ] Code
- [ ] TSDocs
- [ ] TypeScript
- [ ] Unit tests
- [ ] End to end tests
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Open an issue for this feature in the [docs repo](https://github.com/frontity/docs/wiki/Code-Releases)
- [ ] Update community discussions

**Additional Comments**

### CODE REVIEW

**Review by luisherranz — CHANGES_REQUESTED** [review]
I created a workflow in n8n that checks for broken links in all our Readme files (all the repos and packages inside monorepos) to make sure this doesn't happen again.

I run it on the `readme-updates` branch and it seems like there are still some broken links:

1. https://docs.frontity.org/frontity-cli/create in https://github.com/frontity/frontity/tree/readme-updates/packages/core.
2. https://docs.frontity.org/api-reference-1/frontity-yoast in https://github.com/frontity/frontity/tree/readme-updates/packages/yoast.
3. https://docs.frontity.org/frontity-cli/create and https://github.com/frontity/frontity/blob/dev/packages//CHANGELOG.md in https://github.com/frontity/frontity/tree/readme-updates/packages/frontity

_I will update it once we merge this so it points again to `dev` in this monorepo._

Apart from that, there are some empty Readmes that only contain the Community section. I think we should improve those as well:

- https://github.com/frontity/frontity/tree/readme-updates/packages/google-ad-manager
- https://github.com/frontity/frontity/tree/readme-updates/packages/type-declarations

I know you are still working on the new docs, so if you don't consider those a priority, maybe a simple phrase stating what each package is about would be enough.

For `type-declarations` it could be:

> This package is not meant to be installed individually. It contains some type declarations that are imported automatically in Frontity projects.

`@frontity/google-ad-manager` is a regular package. This is the FD: https://community.frontity.org/t/google-ad-manager/1587.

Finally, most of the Readme files use `module.exports` in the examples of `frontity.settings.js`, like this:

```js
module.exports = {
  packages: ["@frontity/html2react"],
};
```

I think that can be misleading because we are not using that syntax anywhere else. Beginners can find it confusing because their `frontity.settings.js` file contains `export default` instead.

I know it is out of the scope of this PR, but do you mind changing those as well?

**Comment by mburridge** [comment]
@luisherranz changes requested at https://github.com/frontity/frontity/pull/655#pullrequestreview-562978315 have been done and awaiting your review. 

There is no documentation for the Yoast package yet, so those links will still be broken and you will still get alerts for them from your script.

**Review by luisherranz — APPROVED** [review]
Thanks Michael, great work 🙂

I have added a comment to the `google-ad-manager` docs issue to make sure we don't forget to update its readme once it is properly documented. I also removed the docs link of `yoast` for now, until it exists:

- https://github.com/frontity/docs/issues/192#issuecomment-756823927
- https://github.com/frontity/docs/issues/220#issuecomment-756825974

Approved! 👍

**Comment by luisherranz** [comment]
I have updated the n8n script that checks for broken links to point to the `dev` branch in this monorepo from now on.

**Pull request merged**
