### PR TITLE
E2E: Use a WP instance in `wp-source-errors` spec file

### LINKED ISSUE #619: End to end tests for wp-source errors (404, 500...)
It seems like the site that Michal created for the wp-source-errors is failing: https://ballistic-western-donkey.glitch.me/status/404?rest_route=/wp/v2/posts?_embed=true&page=1

This is the second time we see this problem. Previously it was with https://httpstatuses.com/ being down. Maybe we should not rely on external sources for our E2E tests.

@michalczaplinski, @DAreRodz: what do you think? Should move those tests to use the WordPress instance to generate the 404 and 500 errors now that we have that possibility?

### PR DESCRIPTION
**Pull request by DAreRodz**
**What**:

Modify the e2e `wp-source-errors` spec to use a WordPress instance. Closes #619 

**Why**:

Not to rely on an external service to mock WP REST API error responses.

**How**:

Adding a snippet to a WP instance with the following code to define a `/status/v1/` endpoint.
```php
<?php
add_action( 'rest_api_init', function () {
  register_rest_route( 'status/v1', '/(?P<status>\\d+)/(:?.+)', array(
    'methods' => 'GET',
    'callback' => function ( $data ) {
      return new WP_Error(
        'mocked_response',
        "Mocked response (status code: {$data['status']}).",
        array( 'status' => (int) $data['status'] )
      );
    },
  ) );
} );
```

**Tasks**:

- [x] End to end tests

**Unrelated Tasks**

- [ ] Code
- [ ] TSDocs
- [ ] TypeScript
- [ ] Unit tests
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Open an issue for this feature in the [docs repo](https://github.com/frontity/docs/wiki/Code-Releases)
- [ ] Update community discussions
- [ ] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Additional Comments**

No changesets as no code was modified, just the e2e tests.

### CODE REVIEW

**Comment by DAreRodz** [comment]
Uhm, tests are not passing. I'll take a look later, moving this to "in progress" again.

**Review by luisherranz — APPROVED** [review]
Perfect! Thanks @DAreRodz!! 🙂

**Comment by luisherranz** [comment]
The E2E tests are failing. Could you please check them out?

**Comment by DAreRodz** [comment]
It was some incorrect assertions. It should work now. :slightly_smiling_face:

**Pull request merged**
