### PR TITLE
Update to React 18

### PR DESCRIPTION
**Pull request by luisherranz**
**What**:

Update to React 18.

**Why**:

To keep up with React.

**How**:

Update all the dependencies and the hydration code.

**Tasks**:

- [x] Code
- [x] Unit tests
- [x] End to end tests
- [x] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Unrelated Tasks**

- [ ] TSDocs
- [ ] TypeScript
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Update community discussions

**Additional Comments**

### CODE REVIEW

**Comment by luisherranz** [comment]
Frontity Connect unit tests are failing. I don't know if its reactivity doesn't work with React 18 or if we need to modify how the tests are written.

**Comment by luisherranz** [comment]
Sites deployed to Vercel seem to work fine:

- https://mars-theme-7sakyizil-frontity.vercel.app/
- https://twentytwenty-theme-oufo0bkeg-frontity.vercel.app/

That's promising.

**Comment by luisherranz** [comment]
Only `use-in-view` e2e tests are failing, which seems odd. But I guess that's also good news 🙂

**Comment by orballo** [comment]
@luisherranz I'll be picking up this task soon :)

**Comment by luisherranz** [comment]
Great 🙂

There is an issue right now when doing the `build` that I haven't solved yet: `error TS2688: Cannot find type definition file for 'minipass'.`

**Comment by orballo** [comment]
@luisherranz In this commit https://github.com/frontity/frontity/pull/932/commits/75ea7588d2a0093c165531a05d54556f7bfbb614
I am using a deprecated version of the AMP validator to sort out the amp e2e tests failing. It is not ideal, but as it is not related to the upgrade of React 18, I think we can carry on with this fix until everything explodes again.

**Comment by orballo** [comment]
@luisherranz The current remaining errors do not seem to be related to React 18. Any idea where they may be coming from?

**Comment by luisherranz** [comment]
> @luisherranz The current remaining errors do not seem to be related to React 18. Any idea where they may be coming from?

Not really, but I can take a look at it next week.

**Comment by luisherranz** [comment]
I am looking at this today. 

The CLI filesystem tests pass fine now.

**Comment by luisherranz** [comment]
The only e2e tests that are not passing locally are `head-tags-yoast-13`. I'm going to remove those, as nobody should be using Yoast 13 with the Head Tags plugin anymore anyway.

**Comment by luisherranz** [comment]
For some reason, GitHub CI is terribly slow (compared to how it was before) and I can't get Cypress e2e tests to pass. There's at least one that fails due to timeouts:

Screenshot 2022-11-22 at 16 40 53

Locally they all pass fine, so if they don't pass this time I'm going to merge the PR anyway.

@orballo, have you already finished?

**Comment by orballo** [comment]
@luisherranz I think my job is done, yeah. I didn't make any changes on React beyond what you did. My work was fixing tests/errors.

**Comment by luisherranz** [comment]
Ok, merged! Thank you for your help @orballo 🙂🎉 

I'll release a new version of beta 2 tomorrow.

**Comment by orballo** [comment]
@luisherranz Thanks a lot for looking into this! :D

**Comment by luisherranz** [comment]
Released as:

- `@frontity/core@2.0.0-beta.2`
- `frontity@2.0.0-beta.1`

**Comment by PeterHaughie** [comment]
Hi @luisherranz can I ask what the difference between beta.1 and beta.2 is please?

**Comment by luisherranz** [comment]
It's just a bump from the previous versions. It doesn't have any real meaning. You can see the changelogs here:

- [core](https://github.com/frontity/frontity/blob/beta/packages/core/CHANGELOG.md)
- [frontity](https://github.com/frontity/frontity/blob/beta/packages/frontity/CHANGELOG.md)

**Pull request merged**
