### PR TITLE
Create `create-frontity` package

### PR DESCRIPTION
**Pull request by luisherranz**
#### Description of what you did:

It looks like now you can do `npm init` to launch a `create-x` project so I thought it'd be great to support that.

#### My PR is a:

- 🚀 New feature

#### Is the PR ready to be merged?

- ✅ Yes!

### CODE REVIEW

**Review by SantosGuillamot — COMMENTED** [review]
Not sure how to check this. Is there a way to test it? Should we add some tests for this command?

**Comment by luisherranz** [comment]
Unfortunately we don't have tests for the CLI commands.

**Review by iamuchejude — CHANGES_REQUESTED** [review]
The e2e test fails.

**Comment by luisherranz** [comment]
Yeah, that problem is solved in this PR: https://github.com/frontity/frontity/pull/338

Sorry I didn't update this one with blocking reason. I'll merge the other one here and I'll re-request your review.

**Comment by luisherranz** [comment]
I've merged the other PR. It should be fine now.

**Review by SantosGuillamot — APPROVED** [review]
>Unfortunately we don't have tests for the CLI commands.

Right, I didn't realize about this. Then it's good for me :slightly_smiling_face: .

**Review by iamuchejude — APPROVED** [review]
Looks good.

**Comment by luisherranz** [comment]
Thanks guys.

**Pull request merged**
