### PR TITLE
Fix handlers if a query is present

### LINKED ISSUE #229: Pages with queries return 404
**_Bug report_**

- [x] I've searched for existing issues
- [x] I've checked documentation: https://docs.frontity.org
- [x] I've checked community forum: https://community.frontity.org

**Describe the expected behavior**

This URL should return the about-us page:
https://mars.frontity.org/about-us/?test=test

**Describe the observed behavior**

It returns a 404.

----

We should add e2e tests for this and ensure it doesn't happen in other type of URLs.

### PR DESCRIPTION
**Pull request by DAreRodz**
#### Description of what you did:

Closes #229.

#### My PR is a:

- 🐞 Bug fix

#### Is the PR ready to be merged?

- Yes

### CODE REVIEW

**Comment by DAreRodz** [comment]
I've just fixed the post type handler and added tests, but the others need to be checked as well. I'm working on it right now.

**Comment by DAreRodz** [comment]
The other handlers work as expected. 👍

**Comment by DAreRodz** [comment]
> @luisherranz said: We should add e2e tests for this and ensure it doesn't happen in other types of URLs.

That means a _dockerized_ WordPress or something is needed for the e2e tests, right? Or could we use https://test.frontity.io instead?

**Review by luisherranz — DISMISSED** [review]
> The other handlers work as expected. 👍

Even tho they work as expected, could you please add unit tests so we don't break them in the future?

>  That means a dockerized WordPress or something is needed for the e2e tests, right? Or could we use https://test.frontity.io instead?

You can use Cypress network stubbing with fixtures for that.

https://docs.cypress.io/api/commands/server.html
https://docs.cypress.io/api/commands/route.html#Fixtures

**Comment by luisherranz** [comment]
I see! Ok, don't worry then. Merge this and we'll figure it later.

**Pull request merged**
