### PR TITLE
Fix Yoast backward compatibility

### PR DESCRIPTION
**Pull request by luisherranz**
**What**:

If we release the data type guard of `isTerm` as it is, it won't work with term custom handlers.

**Why**:

There may be packages that start using `isTerm(data)` to check if a data object is a term or not, like Yoast. Those packages need to be compatible with custom handlers that may have not added `isTerm: true` yet.

**How**:

I added the `isTaxonomy === true` check to the `isTerm` and `isTaxonomy` type guards.

**Tasks**:

- [x] Code
- [x] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)
- [x] TypeScript tests
- [x] Unit tests

**Unrelated Tasks**

- [ ] TSDocs
- [ ] TypeScript
- [ ] End to end tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Open an issue for this feature in the [docs repo](https://github.com/frontity/docs/wiki/Code-Releases)
- [ ] Update community discussions

**Additional Comments**

### CODE REVIEW

**Comment by luisherranz** [comment]
@DAreRodz what do you think? Is this safe or do you see any problems?

**Comment by DAreRodz** [comment]
Oh, nice catch @luisherranz, it's completely safe.

BTW, I added tests for `entity` type guards but not for the `data` ones because they seemed to be pretty straightforward, but maybe in this case we should. Do you think it's necessary? I can add them if you want.

**Comment by luisherranz** [comment]
> Do you think it's necessary? I can add them if you want.

Good idea. Yes please 🙂

**Comment by DAreRodz** [comment]
@luisherranz I've added tests for the data type guards, including tests to check if `isTerm` and `isTaxonomy` work the same with old taxonomy data objects.

Take a look, and if you think everything is OK I'll approve and merge the PR. :blush:

**Review by DAreRodz — APPROVED** [review]
Everything OK.

I added tests for all the data guards if you want to take a look.

**Comment by luisherranz** [comment]
Wow. Impressive tests David. Thanks for that! 👍 😄

**Pull request merged**
