### PR TITLE
Fix fixed dependencies and remove helmet types

### LINKED ISSUE #240: Remove `react-helmet` types in favor of `react-helmet-async`
**_Bug report_**

- [x] I've searched for existing issues
- [x] I've checked documentation: https://docs.frontity.org
- [x] I've checked community forum: https://community.frontity.org

**Describe the expected behavior**

The types of `react-helmet-async` should be included.

**Describe the observed behavior**

The types of `react-helmet` are included

**Possible solution**

Now that `react-helmet-async` has an `index.d.ts` file, we can remove `@types/react-helmet`.
https://github.com/staylor/react-helmet-async/blob/master/index.d.ts

### PR DESCRIPTION
**Pull request by luisherranz**
#### Description of what you did:

I have fixed a problem with e2e installation due to fixed dependencies.

I also take the opportunity to finally remove the types of `react-helmet` in favor of the types of `react-helmet-async`, the package we are currently using.

No changeset is needed because these changes don't affect the implementation of any of the Frontity packages.

#### My PR is a:

- 🐞 Bug fix
- 🔝 Improvement

#### Is the PR ready to be merged?

- ✅ Yes!

### CODE REVIEW

**Comment by luisherranz** [comment]
This is blocking the merge of:
- https://github.com/frontity/frontity/pull/338
- https://github.com/frontity/frontity/pull/337
- https://github.com/frontity/frontity/pull/333
- https://github.com/frontity/frontity/pull/339

**Review by iamuchejude — APPROVED** [review]
LGTM

**Review by SantosGuillamot — APPROVED** [review]
LGTM :slightly_smiling_face:

**Comment by luisherranz** [comment]
Thanks guys :)

**Pull request merged**
