### PR TITLE
Make `@frontity/comscore` package AMP-aware

### LINKED ISSUE #712: Make @frontity/comscore-analytics AMP-aware [5pt]
This is needed for [AMP feature](https://community.frontity.org/t/amp-package/388/). For full context please check out the [final Implementation proposal](https://community.frontity.org/t/amp-package/388/10?u=santosguillamot).

---

The AMP framework uses a special syntax for the [analytics](https://amp.dev/documentation/components/amp-analytics/), so we have to make this package AMP-aware to load the correct content if the AMP package is active.

### PR DESCRIPTION
**Pull request by DAreRodz**
**What**:

Make `@frontity/comscore` package AMP-aware. Close #712 

**Why**:

To make it work when installed along with `@frontity/amp`.

**How**:

Checking if `@frontity/amp` is installed and active, and rendering an `<amp-analytics>` tag for each comscore tracking ID.

**Tasks**:

- [x] Code
- [x] TSDocs
- [x] Unit tests
- [x] End to end tests
- [x] Update community discussions: https://community.frontity.org/t/amp-package/388/64
- [x] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Unrelated Tasks**

- [ ] TypeScript
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages

**Additional Comments**

### CODE REVIEW

**Comment by DAreRodz** [comment]
This PR is ready to review. I've recorded a short video explaining the changes:

<a href="https://www.loom.com/share/46790a7b227c48c980e9cb689c377bed"> <p>Make `@frontity/comscore` package AMP-aware by DAreRodz · Pull Request #737 · frontity/frontity - Watch Video</p>  </a>

**Comment by SantosGuillamot** [comment]
Thanks for the video David :slightly_smiling_face: Just one minor thing I hadn't noticed before: could we add the `frontity-amp` keyword to the [`package.json`](https://github.com/frontity/frontity/blob/amp-comscore/packages/comscore-analytics/package.json#L7)? Now that we are going to start releasing `amp-aware` packages I think we should start using it properly.

**Comment by DAreRodz** [comment]
Sure! I've added the `"frontity-amp"` keyword, @SantosGuillamot.

**Review by luisherranz — APPROVED** [review]
LGTM! Thanks David 👍 🙂

**Pull request merged**
