### PR TITLE
Fix/published post previews

### LINKED ISSUE #876: Setting `source.params.per_page` in state breaks previews of published posts.
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**
Post previews of both drafted and published posts should work as expected even when manually setting `source.params.per_page` to an arbitrary value.

**Observed behavior**

Post previews of published posts breaks bc the previews of published posts are handled with this code:
```javascript
    const response = await libraries.source.api.get({
      endpoint: `${matchedEndpoint}/${id}/revisions?per_page=1`,
      params: state.source.params,
      auth: state.source.auth,
    });
```

Since per_page=1 is manually passed as part of the endpoint, if `state.source.params` contains `per_page` the request will contain duplicated per_page params and thus will result in an error.

**Steps involved to reproduce the problem**
1 - Set up frontity
2 - Set up frontity embedded
3 - Manually set `state.source.params.per_page` to an arbitrary value (in beforeSSR for example)
4 - Try to preview a published post.

**Info about your system**

**Possible solution**

```javascript
    state.source.params.per_page = 1;
    const response = await libraries.source.api.get({
      endpoint: `${matchedEndpoint}/${id}/revisions`,
      params: state.source.params,
      auth: state.source.auth,
    });
```

### PR DESCRIPTION
**Pull request by nicholasio**
**What**:

https://github.com/frontity/frontity/issues/876

**Why**:

Post previews of published posts breaks when manually setting `state.source.params.per_page`

**How**:

**Tasks**:

- [x] Code
- [x] TypeScript
- [x] Unit tests
- [x] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Unrelated Tasks**

- [ ] End to end tests
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Update community discussions
- [ ] TSDocs

**Additional Comments**

### CODE REVIEW

**Comment by nicholasio** [comment]
FYI - prettier ended up making more changes bc latest version of prettier introduced some "breaking changes" and we're setting prettier version to a version range (` "prettier": "^2.0.1",`)

It's recommended to pick a version and stick to it.

**Comment by luisherranz** [comment]
What? Did they introduce breaking changes without releasing a major version? 😕

**Comment by nicholasio** [comment]
> What? Did they introduce breaking changes without releasing a major version? 😕

Yeah, it's actually part of how they recommend using prettier, I guess there weren't truly major breaking changes but just fixes that led to change in formatting.

https://prettier.io/docs/en/install.html#summary

**Comment by luisherranz** [comment]
> It's recommended to pick a version and stick to it.

Ok, let's do that then 🙂

**Comment by luisherranz** [comment]
I've done a PR: https://github.com/frontity/frontity/pull/879

It'll be merged as soon as someone approves it 🙂

**Comment by luisherranz** [comment]
@nicholasio could you please merge `dev` and run prettier again? It's hard to review the PR without seeing clearly the changes. Thanks! 🙂

**Comment by nicholasio** [comment]
> @nicholasio could you please merge `dev` and run prettier again? It's hard to review the PR without seeing clearly the changes. Thanks! 🙂

Done!

**Review by luisherranz — APPROVED** [review]
Perfect. Thanks Nícholas! 🙂👏

Feel free to merge.

**Pull request merged**
