### PR TITLE
Add support to use robots.txt in the root

### PR DESCRIPTION
**Pull request by Koli14**
**What**:

Added a check if a robots.txt exists in the root of the theme, and serve that or the default content.

**Why**:

Empowers developers to change the content of robots.txt

**Feature Discussion:**

https://community.frontity.org/t/use-a-robots-txt-file-in-the-root/1073

**Tasks**:

- [x] Code
- [x] Community discussions
- [x] Changeset
- [x] Add support for this file in our [`now/builder`](https://github.com/frontity/now-builder)
- [x] End to end tests
- [x] Documentation https://github.com/frontity/gitbook-docs/pull/64

**Unrelated**:

- ~TypeScript~
- ~Update starter themes~
- ~Update other packages~
- ~Unit tests~
- ~TypeScript tests~

I never wrote tests, should I write some?

### CODE REVIEW

**Comment by luisherranz** [comment]
Awesome work, thanks @Koli14 🙂 

> I never wrote tests, should I write some?

Yes. Have you ever worked with Cypress?

----

@juanmaguitar I need we need your assistance here. Where should we add this to the docs?

**Comment by Koli14** [comment]
> Yes. Have you ever worked with Cypress?

Not yet. Until now I did not worked with any Test-framework... :S
But in the package.json I see jest, and not Cypress.

**Comment by luisherranz** [comment]
We use both. Jest for unit testing and Cypress for end to end testing :)

@iamuchejude, would you mind adding an e2e test to this? I tried adding a unit test with `mock-fs` based on the work you did in the `createSymlink` function, but it doesn't seem to work with Koa.

**Comment by juanmaguitar** [comment]
> @juanmaguitar I need we need your assistance here. Where should we add this to the docs?

A detailed "Contribution Guide" should be added to this repo. It's already in DevRel's backlog

**Comment by luisherranz** [comment]
> A detailed "Contribution Guide" should be added to this repo.

I mean the information that people can now use a `robots.txt` file in the root of their system if they want.

**Comment by Koli14** [comment]
I did not manage to write test. Should I still try? Or what else need to be done?

**Comment by luisherranz** [comment]
@michalczaplinski could you please take care of unblocking and finishing this PR?

I have added a task to update our `now/builder` as well. This should be similar to what we are doing for the `favicon.ico`:

- https://github.com/frontity/now-builder/blob/master/src/index.ts#L122
- https://github.com/frontity/now-builder/blob/master/src/index.ts#L153

@juanmaguitar we need visibility on what place of the docs we should put this information (that people can now use a robots.txt file in the root of their system if they want).

**Comment by michalczaplinski** [comment]
Hey @Koli14 ! 👋 

I have written the e2e test for this already 🙂 

If you'd like let me know if you want to take a stab at updating the `now-builder` like Luis has mentioned above 

> @michalczaplinski could you please take care of unblocking and finishing this PR?
> 
> I have added a task to update our `now/builder` as well. This should be similar to what we are doing for the `favicon.ico`:
> 
> * https://github.com/frontity/now-builder/blob/master/src/index.ts#L122
> * https://github.com/frontity/now-builder/blob/master/src/index.ts#L153
> 
> @juanmaguitar we need visibility on what place of the docs we should put this information (that people can now use a robots.txt file in the root of their system if they want).

I will update the docs tomorrow and I think this PR should be good to merge.

**Comment by Koli14** [comment]
Thanks @michalczaplinski ! I created a [PR](https://github.com/frontity/now-builder/pull/23) for `now-builder`.

**Comment by michalczaplinski** [comment]
@github-actions run

<details>
<summary>🚀 Merge preview</summary>

```js
// Get pull-req URL like "https://api.github.com/repos/nwtgck/actions-merge-preview/pulls/4"
const pullReqUrl = context.payload.issue.pull_request.url;
const githubUser = context.payload.repository.owner.login;
const res = await fetch(pullReqUrl, {
  headers: [
    ['Authorization', `Basic ${Buffer.from(`${githubUser}:${githubToken}`).toString('base64')}`]
  ]
});
const resJson = await res.json();
const prUserName = resJson.head.user.login;
const baseBranchName = resJson.base.ref;
const branchName = resJson.head.ref;
const fullRepoName = resJson.head.repo.full_name;
const previewBranchName = `actions-merge-preview/${prUserName}-${branchName}`;
execSync(`git config --global user.email "github-actions[bot]@users.noreply.github.com"`);
execSync(`git config --global user.name "github-actions[bot]"`);
// (from: https://stackoverflow.com/a/23987039/2885946)
execSync(`git fetch --all`);
console.log(execSync(`git checkout ${baseBranchName}`).toString());
console.log(execSync(`git checkout -b ${previewBranchName} ${baseBranchName}`).toString());
console.log(execSync(`git pull https://github.com/${fullRepoName}.git ${branchName}`).toString());
// Push preview branch
// NOTE: Force push (should be safe because preview branch always start with "actions-merge-preview/")
execSync(`git push -fu origin ${previewBranchName}`);
const baseRepoFullName = context.payload.repository.full_name;
// Comment body
const commentBody = `🚀 Preview branch:  \n<https://github.com/${baseRepoFullName}/tree/${previewBranchName}>`;
// Comment the deploy URL
await postComment(commentBody);
```
</details>

**Comment by luisherranz** [comment]
> I created a PR for now-builder.

Wow, awesome. Thanks @Koli14!

**Comment by luisherranz** [comment]
I have merged @Koli14's PR and released a new version of `@frontity/now`: https://github.com/frontity/now-builder/pull/23

**Comment by SantosGuillamot** [comment]
Is there something left then?

**Review by luisherranz — CHANGES_REQUESTED** [review]
The only thing I think we need is an e2e test for the case where there's a file.

It looks like we could use this Cypress API: https://docs.cypress.io/api/commands/writefile.html#Syntax

@michalczaplinski, could you take a look at that?

**Comment by michalczaplinski** [comment]
> The only thing I think we need is an e2e test for the case where there's a file.
> 
> It looks like we could use this Cypress API: https://docs.cypress.io/api/commands/writefile.html#Syntax
> 
> @michalczaplinski, could you take a look at that?

sure :)

**Comment by michalczaplinski** [comment]
> The only thing I think we need is an e2e test for the case where there's a file.

done.

**Review by luisherranz — APPROVED** [review]
Awesome! Ready to merge then.

Thanks @michalczaplinski for the test, thanks @juanmaguitar for the docs and thanks @Koli14 for the PR! 😄

**Pull request merged**
