### PR TITLE
Fix webpack bundling issues

### PR DESCRIPTION
**Pull request by luisherranz**
#### Description of what you did:

I got rid of some Webpack warnings that come up when bundling `server.js` and I also cleaned up a bit some of those files.

#### My PR is a:

- 🔝 Improvement

#### Is the PR ready to be merged?

- ✅ Yes!

### CODE REVIEW

**Review by DAreRodz — APPROVED** [review]
Everything good. 👌

PS: I've changed the name of a type just to capitalize it.

**Comment by luisherranz** [comment]
Thanks @DAreRodz!

**Comment by luisherranz** [comment]
Blocked by an e2e problem with npm install that will be solved once we merge https://github.com/frontity/frontity/pull/338.

**Comment by luisherranz** [comment]
Thanks @DAreRodz!

**Pull request merged**
