### PR TITLE
Add lerna-changelog & generate the first changelog

### PR DESCRIPTION
**Pull request by michalczaplinski**
**What**:

- Add [`lerna-changelog` ](https://github.com/lerna/lerna-changelog/blob/master/CHANGELOG.md)
- Add the script to generate the changelog.
- Add the global `CHANGELOG.md` that includes all the changes to all packages in one place.

Based on the discussion in https://community.frontity.org/t/add-changelog-in-the-releases-github-page/1692

**Why**:

- To have a centralized place to see all the changes in our packages.
- To be able to link to a unified changelog from our website and other places.

**Tasks**:

- [x] Code

### CODE REVIEW

**Review by luisherranz — CHANGES_REQUESTED** [review]
Is this ready to review? It doesn't seem to be working yet, right?

1. Everything seems to be a `bug` (patch), even minor updates (features).
1. It seems like it doesn't include the proper changes, for example, this is our `wp-source@1.7.0` changelog:

---

## 1.7.0

### Minor Changes

- [`9b7858ba`](https://github.com/frontity/frontity/commit/9b7858ba283c1780037eb7519f459b01363cca54) [#382](https://github.com/frontity/frontity/pull/382) Thanks [@DAreRodz](https://github.com/DAreRodz)! - Add an option called `authorBase` to change the base of author links. Useful when a custom structure for permalinks is set in the WordPress site connected with the `@frontity/wp-source` package.

---

Source: https://github.com/frontity/frontity/blob/dev/packages/wp-source/CHANGELOG.md

But this is the output of this package:

## @frontity/wp-source@1.7.0 (2020-04-24)

#### :bug: Bug Fix

- `tiny-router`
  - [#321](https://github.com/frontity/frontity/pull/321) fixes `popstate` handler when state is null for `#element`-like links ([@orballo](https://github.com/orballo))
- `create-frontity`
  - [#349](https://github.com/frontity/frontity/pull/349) Add bin property to `create-frontity` ([@luisherranz](https://github.com/luisherranz))

---

**Comment by michalczaplinski** [comment]
> Everything seems to be a bug (patch), even minor updates (features).
> It seems like it doesn't include the proper changes, for example, this is our wp-source@1.7.0 changelog:

Damn, you're right Luis 😓 

I ll investigate why that is the case but will deprioritize this for now to focus on Sprint tasks and e2e tests.

**Comment by luisherranz** [comment]
Should we close this?

**Comment by michalczaplinski** [comment]
yes, let's close this for now, we can re-open the PR if this will be needed again.

**Pull request closed without merging**
