### PR TITLE
Fix react helmet async update

### PR DESCRIPTION
**Pull request by luisherranz**
**What**:

I have moved the code that pins the react-helmet-async dependency to 1.0.4 from @michalczaplinski browser tab PR: https://github.com/frontity/frontity/pull/374

**Why**:

Because in the latest release they have broken the types in index.d.ts and it causes an error on npm install in our repository.

**How**:

It's now a fixed dependency. We need to revert this change once this PR is merged: https://github.com/staylor/react-helmet-async/pull/91

**Tasks**:

- [x] Code
- [ ] ~TypeScript~

- [ ] ~Unit tests~
- [ ] ~End to end tests~
- [ ] ~TypeScript tests~

- [ ] ~Update starter themes~
- [ ] ~Update other packages~

- [ ] ~Documentation~
- [ ] ~Community discussions~

- [ ] ~Changeset~ : Doesn't need a changeset because it doesn't affect user code.

### CODE REVIEW

**Review by DAreRodz — APPROVED** [review]
:ok_hand:

**Comment by DAreRodz** [comment]
By the way, the `code` task is not striked out, but is not checked as well. I guess that task is complete so I did it by myself.

**Comment by luisherranz** [comment]
Yes, sorry about that :)

**Comment by luisherranz** [comment]
I will add the GH action for tasks in this repo as well.

**Pull request merged**
