### PR TITLE
Improve Accessibility Score in Lighthouse

### PR DESCRIPTION
**Pull request by DAreRodz**
Some minor changes to improve the Lighthouse Accessibility score.

### CODE REVIEW

**Comment by luisherranz** [comment]
Lovely.

**Comment by luisherranz** [comment]
@DAreRodz do you want us to release this now or do you prefer to wait until more features are added?

**Comment by DAreRodz** [comment]
Uhm, I prefer to release this now and add more features later.

**Comment by luisherranz** [comment]
Ok, let us know once it's ready.

**Comment by luisherranz** [comment]
I'll wait until then.

**Comment by luisherranz** [comment]
I'm going to do the release. We'll add this to a future one.

**Comment by luisherranz** [comment]
I've opened an issue to discuss progress: https://github.com/frontity/frontity/issues/108

**Review by luisherranz — APPROVED** [review]

**Pull request merged**
