### PR TITLE
Remove unnecessary css array

### PR DESCRIPTION
**Pull request by luisherranz**
**What**:

Remove an unnecessary css array.

**Why**:

It is not doing anything, so it is confusing for people looking at the code. They may think that it is required.

**How**:

I just removed the unnecessary part.

**Tasks**:

- [x] Code
- [x] Changeset

**Unrelated**:

- TypeScript
- Unit tests
- End to end tests
- TypeScript tests
- Update starter themes
- Update other packages
- Documentation
- Community discussions

### CODE REVIEW

**Review by SantosGuillamot — CHANGES_REQUESTED** [review]
Thanks for the quick fix :slightly_smiling_face: I guess we'll need a changeset right?

**Comment by luisherranz** [comment]
You're absolutely right.

Done 👍

**Review by SantosGuillamot — APPROVED** [review]
Great :+1:

**Review by michalczaplinski — COMMENTED** [review]
👍

**Review by michalczaplinski — APPROVED** [review]

**Pull request merged**
