### PR TITLE
Analytics packages documentation in README.md's

### PR DESCRIPTION
**Pull request by juanmaguitar**
**What**:

README's of Analytics package as part of https://github.com/frontity/docs/issues/151

**Why**:

To have this packages properly documented

**How**:

By adding the proper info to these README.md's

**Tasks**:

- [X] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Unrelated Tasks**

- [ ] Code
- [ ] TSDocs
- [ ] TypeScript
- [ ] Unit tests
- [ ] End to end tests
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Open an issue for this feature in the [docs repo](https://github.com/frontity/docs/wiki/Code-Releases)
- [ ] Update community discussions

**Additional Comments**

Related to https://github.com/frontity/docs/pull/226

### CODE REVIEW

**Review by DAreRodz — APPROVED** [review]
It's great, @juanmaguitar :clap:

**Comment by DAreRodz** [comment]
Uhm, unit tests are failing but @juanmaguitar didn't change anything in the code. @michalczaplinski, could you take a look at this?

**Comment by juanmaguitar** [comment]
@DAreRodz @michalczaplinski Can I merge this PR?

**Comment by DAreRodz** [comment]
Yes @juanmaguitar, go ahead. :+1:

**Comment by juanmaguitar** [comment]
@SantosGuillamot when do you think these changes can be released? 
I'm linking to these README's from https://github.com/frontity/docs/pull/226

**Comment by michalczaplinski** [comment]
@DAreRodz My bad, I've missed this PR! Thanks for taking care of this 😊

**Comment by SantosGuillamot** [comment]
>@SantosGuillamot when do you think these changes can be released?

We're planning to do a release today, so they should be available then.

**Pull request merged**
