### PR TITLE
Fix excluded transpilation in windows

### PR DESCRIPTION
**Pull request by luisherranz**
**What**:

Change module and ts-node exclude regexps to work with backslashes as well.

**Why**:

Because we need to take into account that paths in Windows contain backslashes: `folder\file.js`.

**How**:

Simply by changing the regular expression to take into account that case. From `\/` to `(\/|\\)`.

**Tasks**:

- [x] Code
- [x] Unit tests
- [x] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Unrelated Tasks**

- [ ] TSDocs
- [ ] TypeScript
- [ ] End to end tests
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Update community discussions

**Additional Comments**

### CODE REVIEW

**Comment by luisherranz** [comment]
@darerodz, could you please check if this fixes the Windows problem?

**Comment by ClaudioAlcantaraR** [comment]
@luisherranz Hola Luis. Para saber si el problema se ha solucionado solo debo descargar frontity otra vez? Perdona si me pregunta carece de sentido, soy nuevo en esto

**Comment by luisherranz** [comment]
Hey @ClaudioAlcantaraR, thanks for helping out. You can follow these steps 🙂 

- Clone the `frontity/frontity` repo on your local machine.
- Switch to the `fix-excluded-transpilation-in-windows` branch.
- Run `npm install` (only from the root folder).
- Run `cd projects/mars-theme`.
- Run `npx frontity dev` to start Frontity on `localhost:3000`.

**Comment by luisherranz** [comment]
Awesome. Thanks David 🙂

**Comment by ClaudioAlcantaraR** [comment]
> Hey @ClaudioAlcantaraR, thanks for helping out. You can follow these steps 🙂
> 
> * Clone the `frontity/frontity` repo on your local machine.
> * Switch to the `fix-excluded-transpilation-in-windows` branch.
> * Run `npm install` (only from the root folder).
> * Run `cd projects/mars-theme`.
> * Run `npx frontity dev` to start Frontity on `localhost:3000`.

Thanks Luis. I try it but I had a few problems after run npm install, I guess I have to wait for next frontity update

**Review by DAreRodz — APPROVED** [review]
Perfect, thanks for the quick fix, @luisherranz 🙌

PS: you removed some paths for `.ts` files in the last two tests, I don't know if that was intentional.

**Comment by luisherranz** [comment]
> PS: you removed some paths for .ts files in the last two tests, I don't know if that was intentional.

Yes, those were wrong. I think I introduce them in the refactoring and I spotted then afterward 🙂

**Pull request merged**
