### PR TITLE
Add the connect API for React component

### PR DESCRIPTION
**Pull request by luisherranz**

### CODE REVIEW

**Comment by luisherranz** [comment]
I've finished this PR but it was made on top of https://github.com/frontity/frontity/pull/32 so it has to wait until it's merged.

If you want you can take a look at the implementation here https://github.com/frontity/frontity/pull/38/commits/f85bf69b11ece72bf4db082d6456c8403374f974 and here https://github.com/frontity/frontity/pull/38/commits/130cd58718e0f35661e91575de08bcd987bb8c4b.

**Comment by luisherranz** [comment]
Ok, now that #32 has been merged, this is ready for review! @orballo @DAreRodz

**Review by DAreRodz — APPROVED** [review]
👌

**Comment by luisherranz** [comment]
Thanks!

**Pull request merged**
