### PR TITLE
Changes in the CLI

### PR DESCRIPTION
**Pull request by orballo**
- [x] Install `favicon.ico` on `frontity create`.
- [x] Implement a `subscribe` function.

### CODE REVIEW

**Review by luisherranz — CHANGES_REQUESTED** [review]
When I do `npm start create` I get this error:
Screen Shot 2019-05-07 at 12 05 50

When I do `npm dev create` it works, but the `package.json` contains an `undefined` package:
```
  "dependencies": {
    "frontity": "^1.0.0",
    "undefined": "^0.1.0",
    "@frontity/mars-theme": "./packages/mars-theme"
  }
```

**Comment by luisherranz** [comment]
Is it a good idea to change this line:
Screen Shot 2019-05-07 at 12 07 28

to **`cd my-project && frontity dev`** to avoid confusion?

**Comment by luisherranz** [comment]
It's working great now.

I guess the final `frontity.settings.js` and `package.json` can't be done until we publish `@frontity/tiny-router` and `@frontity/wp-source`, right?

**Comment by orballo** [comment]
> It's working great now.
> 
> I guess the final `frontity.settings.js` and `package.json` can't be done until we publish `@frontity/tiny-router` and `@frontity/wp-source`, right?

Yeah, I'd do that.

**Review by luisherranz — APPROVED** [review]
Ok, approved then :)

**Review by luisherranz — DISMISSED** [review]
I've updated the forum topic with more info:
https://community.frontity.org/t/beta-frontity-cli-create-command/143/18

----

If we transpile the typescript code to javascript, it cannot access the `frontity.settings.ts` file.

So either we:
1. Don't transpile the `frontity` code and run it using `ts-node`.
1. Transpile `frontity.settings.ts` with `tsc` before Frontity starts.

@orballo can you take a look at it?

I think I'll try the first one first. `ts-node` has a programmatic option: https://github.com/TypeStrong/ts-node#programmatic.
- It can work with `require('ts-node').register()` inside the code
- It can work with `node -r ts-node/register` in the command line.

EDIT: Uh, and it has a `transpile-only` option :)

**Review by DAreRodz — APPROVED** [review]
👍

**Pull request merged**
