### PR TITLE
Add HMR flag to Frontity state and fix router changing URL on HMR

### LINKED ISSUE #782: HMR loads the data object that was used in SSR rather than re-using the data object for the current link
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

Upon making an edit to a theme file when you save the file the live server should re-render the page that is currently displayed in the browser.

**Observed behavior**
Instead, it renders the page that was used in the SSR.

**Steps involved to reproduce the problem**

Run `npx frontity dev` from a new project.

Navigate to a page other than the home page.

Make an edit to any theme file, a file within the `packages` directory that will cause the live server to re-render the page in the browser.

* See this question in the community: https://community.frontity.org/t/on-saved-changes-the-page-reloads-always-the-homepage/4383

**Info about your system**

## System:
 - OS: macOS 11.2.3
 - CPU: (8) x64 Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz
 - Memory: 1.55 GB / 16.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 14.15.4 - ~/.nvm/versions/node/v14.15.4/bin/node
 - npm: 7.5.2 - ~/.nvm/versions/node/v14.15.4/bin/npm
## Browsers:
 - Chrome: 89.0.4389.114
 - Edge: Not Found
 - Firefox: 87.0
 - Safari: 14.0.3
## npmPackages:
 - @frontity/core: ^1.11.1 => 1.11.1 
 - @frontity/html2react: ^1.6.2 => 1.6.2 
 - @frontity/mars-theme: ./packages/mars-theme => 1.5.0 
 - @frontity/tiny-router: ^1.4.1 => 1.4.1 
 - @frontity/wp-source: ^1.11.2 => 1.11.2 
 - frontity: ^1.14.3 => 1.14.3 
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found

**Possible solution**

### PR DESCRIPTION
**Pull request by luisherranz**
**What**:

I have added a flag to the Frontity state so packages can know if the current code is run under an HMR refresh.

I have also used that flag to skip doing a URL change in the `tiny-router` initialization.

**Why**:

Because `tiny-router` was replacing the URL of window.location and it shouldn't do it in an HMR refresh.

**How**:

Just adding a `state.frontity.hmr` flag to the state, which is false by default, then switching it to true on the client when an HMR refresh is triggered.

**Tasks**:

- [x] Code
- [x] TSDocs
- [x] TypeScript
- [x] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Unrelated Tasks**

- [ ] Unit tests
- [ ] End to end tests
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Update community discussions

**Additional Comments**

I haven't added any e2e test because I don't know how to test HMR with Cypress. I guess it's not super important for now...

### CODE REVIEW

**Comment by luisherranz** [comment]
This is my proposal to fix the #782 bug. Let me know what you think.

https://www.loom.com/share/346e70a1b9294fa59bbcdce3b337a290

**Review by michalczaplinski — APPROVED** [review]
Looks good to me. Thanks Luis! 👍

**Comment by cristianbote** [comment]
I was looking over this PR and thought if maybe we could pass `hmr: true` directly from the generated hot module template for the client instead?

Recorded a video https://www.loom.com/share/8c3fc3b0af62404e97b17872facb81fc

**Comment by luisherranz** [comment]
Yeah, that's a much better idea, I'll make the change. Thanks Cristian 🙂

I still think that having the flag in `state.frontity.hmr` is better than passing it to `init` actions because maybe it is needed in other parts of a package, like React components.

**Comment by cristianbote** [comment]
> I still think that having the flag in `state.frontity.hmr` is better than passing it to `init` actions because maybe it is needed in other parts of a package, like React components.

Oh I agree. Passing it to `init` might just solved it for now, if any, but not for the future. 👍

**Comment by luisherranz** [comment]
Done 👍 

@michalczaplinski: do you want to review it again?

**Review by michalczaplinski — APPROVED** [review]
Good idea @cristianbote, looks fine to me! 👍

**Pull request merged**
