### PR TITLE
Fix performance warning appearing in development

### PR DESCRIPTION
**Pull request by luisherranz**
**What**:

I have removed the `performance.hints` field I added in https://github.com/frontity/frontity/pull/547.

**Why**:

Apparently that adds the warning also in development mode. It's the default anyway.

**How**:

By simply removing it from the Webpack configuration.

**Tasks**:

- [x] Code
- [x] Unit tests

No changeset is necessary because this is a fix for an unreleased PR: https://github.com/frontity/frontity/pull/547

**Unrelated Tasks**

- [ ] End to end tests
- [ ] TSDocs
- [ ] TypeScript
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Open an issue for this feature in the [docs repo](https://github.com/frontity/docs/wiki/Code-Releases)
- [ ] Update community discussions
- [ ] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

### CODE REVIEW

**Review by DAreRodz — COMMENTED** [review]
So just removing that property makes webpack throw a performance warning only in production mode? Just to be sure.

**Comment by luisherranz** [comment]
That's right. I guess it is Webpack's default behavior and I broke it by explicitly defining the property.

**Review by DAreRodz — APPROVED** [review]
Approved then. :heavy_check_mark:

**Comment by luisherranz** [comment]
Thanks @DAreRodz!

**Pull request merged**
