### PR TITLE
Catch error whill returning result in getMatch function

### PR DESCRIPTION
**Pull request by jeanettepraninPF**
**What**:

Adding a try/catch in the wp-source get-match.ts file, because the "extractParameters" function can cause the following error:
TypeError: Cannot read property 'slice' of null
      at extractParameters (webpack-internal:///./node_modules/@frontity/wp-source/src/libraries/get-match.ts:16:34)

**Why**:

Instead of returning a 404 Not Found error, the code is returning a 500 Internal Server error. Please see https://trashisfortossers.com/2015/07/day-1-upstate-new-york.html?spref=pi as an example.

**How**:

On my own personal fork and tested.

**Tasks**:

- [ ] Code
- [ ] TSDocs
- [ ] TypeScript
- [ ] Unit tests
- [ ] End to end tests
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Open an issue for this feature in the [docs repo](https://github.com/frontity/docs/wiki/Code-Releases)
- [ ] Update community discussions
- [ ] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Unrelated Tasks**

**Additional Comments**

### CODE REVIEW

**Comment by luisherranz** [comment]
Hey @jeanettepraninPF, many thanks for the PR!!

May I know which pattern is making the `extractParameters` function to fail? I guess the URL is `/2015/07/day-1-upstate-new-york.html?spref=pi`, right?

I'd love to understand more why this is failing and if returning a 404 is the correct behavior 🙂

**Comment by jeanettepraninPF** [comment]
Hi @luisherranz! The reason why I think this should be returning a 404 instead of a 500 is because the URL is a valid Wordpress URL, although this specific article has been hidden so it is not available to the public.

**Comment by SantosGuillamot** [comment]
Thanks for the PR @jeanettepraninPF :slightly_smiling_face: In case it helps, it seems it's the query `?spref=pi` the one causing the 500:

* This returns a 404 -> https://trashisfortossers.com/2015/07/day-1-upstate-new-york.html
* This returns an Internal Server Error -> https://trashisfortossers.com/2015/07/day-1-upstate-new-york.html?spref=pi

I guess both should return a 404 right?

**Comment by luisherranz** [comment]
This seems to work just fine: https://mars.frontity.org/not-existent-page/?spref=pi

@jeanettepraninPF please add a list of your patterns here so we can take a look.

**Comment by jeanettepraninPF** [comment]
@luisherranz 
For my common settings in Wordpress, we have the "Post name" selected --> "https://www.trashisfortossers.com/sample-post/"

We have these patterns as well:
pattern: "/articles/:post_name/:id",
pattern: "/videos/",
pattern: "/style/",
pattern: "/home-and-living/",
pattern: "/diy-and-guides/",
pattern: "/ceo-diaries/"

These are all initialized in actions --> theme --> init in the twentytwenty-theme/src/index.js
`libraries.source.handlers.push(articleHandler, videosHandler, styleHandler, homeAndLivingHandler, diyHandler, ceoDiariesHandler);`

**Comment by luisherranz** [comment]
Thanks @jeanettepraninPF. I was able to debug this directly in https://www.trashisfortossers.com/ and I found that the pattern that is catching `/2015/07/day-1-upstate-new-york.html?spref=pi` is `"attachment from post by day"` which is `"/:year(\d+)/:month(\d+)/:day(\d+)?/:postSlug(.*\D.*)/:slug"` and it's doing so because it's using the query `?spref=pi` as the final `:slug` part. Then, it fails because we are removing the query in the `extractParameters` function:

https://github.com/frontity/frontity/blob/7e99b9b4a7d1bb8d3e02d3b7bce587bb8f400bee/packages/wp-source/src/libraries/get-match.ts#L19-L23

So this is finally a duplicate of https://github.com/frontity/frontity/issues/596 and once that is solved, it should return a 404.

Jeanette, would you be willing to help us solve that bug instead? I'll add more information about how to solve it in the issue.

Regarding this PR, once we fix the #596 bug it shouldn't be necessary to try/catch the return of `getMatch` because it should never fail, so I prefer to leave it as it is because if it fails for someone else in the future it means there's another bug, so I'm closing it now. Feel free to reopen it if you if there's something else we're not aware of  🙂

**Comment by jeanettepraninPF** [comment]
@luisherranz Got it. Reading that bug, it seems like DAreRodz's solution should work. Thanks for your help! Is this something that may come out in an update soon?

**Comment by luisherranz** [comment]
It's rated as `priority: medium` right now so it'd be awesome if you could help us out with it 🙂

**Pull request closed without merging**
