### PR TITLE
Fix link mismatch

### LINKED ISSUE #623: state.router.link mismatch when the URL is not the same in the server as in the client
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

`state.router.link` should have the URL of the client.

**Observed behavior**

`state.router.link` has the URL that was sent to the server.

**Steps involved to reproduce the problem**

Add this to the Frontity server:

```js
// Change a query in the server.
if (ctx.URL.searchParams.get("utm")) {
  ctx.URL.searchParams.set("utm", "SERVER");
}
```

And visit http://localhost:3000/?utm=client. `state.router.link` is http://localhost:3000/?utm=SERVER and the URL is also replaced in the browser bar.

**Possible solution**

I think the way to go would be to:

- Solve the problem of the canonical links not pointing to the same data object.
- Restore the `state.router.link` to the client URL in the hydration.

I have explained it in more detail here:

- Video: https://www.loom.com/share/707af27e0c0f4d7db7d4551c98d5f7f8
- Drawing: https://excalidraw.com/#json=5474711555276800,KVqzcQvObG8FHpK0kMujrg

A quick fix would be to remove this line to now replace the client URL with the `state.router.link` value that was sent to the server, but that would break the "Back" button of the browser:

https://github.com/frontity/frontity/blob/dev/packages/tiny-router/src/actions.ts#L90

- You visit `/?utm=client`
- The server receives `/?utm=SERVER`
  - `state.router.link` is `/?utm=SERVER`
  - The data object is for `/?utm=SERVER`
- The client still has `/?utm=client` in the browser bar, but `state.router.link` is `/?utm=SERVER`
- You go forward to some link
- You go back with the browser button to `/?utm=client`. There is no data object for that URL.

We could alleviate the problem by using the autoFetch in the `"pop"` method, here: https://github.com/frontity/frontity/blob/dev/packages/tiny-router/src/actions.ts#L50-L61. That way, at least the page (`/?utm=client`) will be fetched again.

Also, we would need to remove `state.router.link` from the `updateState` action that is going to be introduced with the infinite scroll hooks: https://github.com/frontity/frontity/blob/infinite-scroll-beta/packages/tiny-router/src/actions.ts#L96

### PR DESCRIPTION
**Pull request by DAreRodz**
**What**:

Closes #623 

**Why**:

To avoid an issue when the Frontity server returns the state with a `state.router.link` that doesn't match the current URL. 

**How**:

Changing the `actions.router.init()` function in `@frontity/tiny-router` so
- it replaces `state.router.link` with the link in the browser if a different one has come from the server.
- it makes the new value of `state.router.link` to point to the correct data object in `state.source.data`.

**Tasks**:

- [x] Code
- [x] Unit tests
- [x] End to end tests
- [x] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Unrelated Tasks**

- [ ] TSDocs
- [ ] TypeScript
- [ ] TypeScript tests
- [ ] Update starter themes
- [ ] Update other packages
- [ ] Open an issue for this feature in the [docs repo](https://github.com/frontity/docs/wiki/Code-Releases)
- [ ] Update community discussions

**Additional Comments**

### CODE REVIEW

**Review by michalczaplinski — COMMENTED** [review]
OK, I've reviewed and tested it and everything looks perfectly fine to me which makes me think that maybe I've missed something. That's a comment on my reviewing skill and not your coding, I think you did an awesome job @DAreRodz :) 

@luisherranz Could you also give it a quick look before I approve it?

**Comment by luisherranz** [comment]
> OK, I've reviewed and tested it and everything looks perfectly fine to me which makes me think that maybe I've missed something. That's a comment on my reviewing skill and not your coding, I think you did an awesome job @DAreRodz :)
> 
> @luisherranz Could you also give it a quick look before I approve it?

Hey Michal, no, not really. I am sure the review is fine. And if it is not, we will find out and fix it later.

**None of us make bulletproof reviews and that is absolutely fine**. It is part of the job. Things are going to slip off sometimes and we will discover them later, file bugs, and fix them. There is nothing wrong with that process. The only thing we can do is to try to do our best at the moment, and learn as much as we can when something slips off to improve for the next time. And that's it. The rest is not up to us.

**Comment by michalczaplinski** [comment]
> > OK, I've reviewed and tested it and everything looks perfectly fine to me which makes me think that maybe I've missed something. That's a comment on my reviewing skill and not your coding, I think you did an awesome job @DAreRodz :)
> > @luisherranz Could you also give it a quick look before I approve it?
> 
> Hey Michal, no, not really. I am sure the review is fine. And if it is not, we will find out and fix it later.
> 
> **None of us make bulletproof reviews and that is absolutely fine**. It is part of the job. Things are going to slip off sometimes and we will discover them later, file bugs, and fix them. There is nothing wrong with that process. The only thing we can do is to try to do our best at the moment, and learn as much as we can when something slips off to improve for the next time. And that's it. The rest is not up to us.

Gotcha, I think I wasn't confident that I haven't missed something, like I said. But you're right that we have to just "trust the process" :)

**Review by michalczaplinski — APPROVED** [review]
👍

**Pull request merged**
