### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by rmartinezduque**
**What**:

I've rewritten and reorganized the README.md file as it was a bit outdated.

**Why**:

To update sections (such as 'How does Frontity work' and 'How is Frontity organized') and include links to the new documentation and other learning resources.

### CODE REVIEW

**Comment by juanmaguitar** [comment]
@rmartinezduque Thanks a lot! It looks great. 

I think this repository README should also inform the developers of things such as:
- The content of the repository
- Some technical details and design principles of the project
- How to download the project and launch it locally
- How to launch the tests

I have already documented some of the topics in the WIKI of this repo https://github.com/frontity/frontity/wiki so we could use this document to connect all these detailed explanations for each topic.

I would add some subsections to this README to draw the attention on these topics

**Review by juanmaguitar — APPROVED** [review]

**Comment by rmartinezduque** [comment]
> I would add some subsections to this README to draw the attention on these topics

Sure, I think that's a great idea. Although my suggestion is keeping the information here as much simple as possible. E.g. Instead of going into the details of the design principles, just highlighting them and adding a link where users can find more info. It's not the same but I like what [Blitz does here](https://github.com/blitz-js/blitz#the-foundational-principles) with the Foundational Principles and their manifesto.

> How to download the project and launch it locally

Maybe it makes sense to include this in the Getting Started section.

Anyway, feel free to make any additional changes you consider :)

**Comment by rmartinezduque** [comment]
By the way @juanmaguitar, there's a 'New document' headline at the top of the README that shouldn't be there, it's a typo. Could you please delete it? Thanks!

**Comment by juanmaguitar** [comment]
> Could you please delete it? Thanks!
Done! 👍

**Pull request merged**
