### PR TITLE
Version Packages

### PR DESCRIPTION
**Pull request by frontibotito**
This PR was opened by the [Changesets release](https://github.com/changesets/action) GitHub action. When you're ready to do a release, you can merge this and the packages will be published to npm automatically. If you're not ready to do a release yet, that's fine, whenever you add more changesets to master, this PR will be updated.

# Releases

### Minor Changes

- [`2f988427`](https://github.com/frontity/frontity/commit/2f9884270490d1a67c3ba6f061831b24ae4cc038) [#826](https://github.com/frontity/frontity/pull/826) Thanks [@michalczaplinski](https://github.com/michalczaplinski)! - Make the Image component from `@frontity/components` AMP-aware and remove the Intersection Observer fallback which used to lazily load images in the absence of native lazy loading.

### Patch Changes

- [`a154a9cb`](https://github.com/frontity/frontity/commit/a154a9cb7093ab0199c01f28b6363f93427abb17) [#840](https://github.com/frontity/frontity/pull/840) Thanks [@luisherranz](https://github.com/luisherranz)! - Fix Webpack/TS-Node excludes not working on Windows.
- [`63154b4f`](https://github.com/frontity/frontity/commit/63154b4fb16095ccf22e4862c6d91c9c6157af67) [#837](https://github.com/frontity/frontity/pull/837) Thanks [@luisherranz](https://github.com/luisherranz)! - Fix transpilation of `frontity.config.js` files in external packages.

### CODE REVIEW

**Review by SantosGuillamot — APPROVED** [review]

**Comment by luisherranz** [comment]
#837 is the fix that makes #834 not needed anymore 😆

I'm going to push a revert of that PR.

**Comment by luisherranz** [comment]
I think that fixes it.

**Comment by SantosGuillamot** [comment]
Okay, great. Thanks @luisherranz  :slightly_smiling_face:

**Comment by DAreRodz** [comment]
The `create-symlinks` tests in `@frontity/core` were failing (see [this](https://github.com/frontity/frontity/pull/842/checks?check_run_id=2735047082)). They were failing in my local environment as well, and I've made them pass just updating the package-lock file.

Let's see if that fixes the error.

**Comment by DAreRodz** [comment]
Uhm, weird, I didn't fix anything... :thinking:

**Comment by SantosGuillamot** [comment]
Mmm, if they are passing locally, could be something related to npm? I remember we have had issues in the past because we use npm 7 and GitHub actions use npm 6.

**Comment by DAreRodz** [comment]
> Mmm, if they are passing locally, could be something related to npm? I remember we have had issues in the past because we use npm 7 and GitHub actions use npm 6.

Actually it's failing with node 16 and npm 7.

**Comment by DAreRodz** [comment]
OK, I didn't try with those versions before. :see_no_evil:

Not it fails in my local env with a more related error: `Error: write EBADF`.

**Comment by DAreRodz** [comment]
> It doesn't seem specific to this particular PR because I just pushed to this other one and it also failed: #836

I've created a PR that seems to fix the issue: https://github.com/frontity/frontity/pull/843

**Pull request closed without merging**
