### PR TITLE
Add error component showing how to handle 404 and other errors

### LINKED ISSUE #298: Add React component for isError to Mars and TwentyTwenty
**Feature:** [Add status code and error messages to data](https://community.frontity.org/t/add-status-code-and-error-messages-to-data/1125)
**User Story**: Show how to work with isError in a theme

- [ ] Add React logic to show people how to manage `isError` in their themes on Mars.
- [ ] Add React logic to show people how to manage `isError` in their themes on TwentyTwenty.

[Sprint Card](https://github.com/orgs/frontity/projects/2#card-32117718)

### PR DESCRIPTION
**Pull request by michalczaplinski**
#### Description of what you did:

fixes #298 

#### My PR is a:

- 🔝 Improvement

#### Is the PR ready to be merged?

- ✅ Yes!

### CODE REVIEW

**Review by luisherranz — APPROVED** [review]
Thanks @michalczaplinski! Everything looks fine to me 👍 

I took the opportunity to add some e2e tests for wp-source errors and fix some TypeScript inconsistencies.

**Comment by DarkChris86** [comment]
Hey guys,

https://twentytwenty.frontity.org/category/inspiring-stories/asd
**Internal server error**

I've checked it local side and on your live site this error handling function, and found this bug:
TypeError: Cannot read property 'source' of undefined at ErrorPage (webpack-internal:///./packages/webmernok-theme/src/components/page-error.js:10:46)

**Comment by luisherranz** [comment]
Hey @DarkChris86, it looks like @SantosGuillamot opened a PR to fix that a couple of days ago: https://github.com/frontity/frontity/pull/358 🙂

**Comment by DarkChris86** [comment]
Thanks it works properly with connect, thanks!  ; )

**Pull request merged**
