### PR TITLE
Add option to skip favicon on npx frontity create

### LINKED ISSUE #861: Error when creating new project in China due to the failure on downloading favicon.ico
**_Bug report_**

- I've updated both my project and my packages to the latest Frontity versions: https://docs.frontity.org/guides/keep-frontity-updated
- I've searched for existing issues.
- I've checked the documentation: https://docs.frontity.org
- I've checked the community forum: https://community.frontity.org

**Expected behavior**

**Observed behavior**

**Steps involved to reproduce the problem**

Just using `npx frontity create`

then throw `Error: request to https://favicon.frontity.org/ failed, reason: connect ECONNREFUSED 76.76.21.21:443`

because `https://favicon.frontity.org/` is not accessible in China.

After setting up a proxy in Terminal using `http_proxy` and `https_proxy`, it's still not working.

image

**Info about your system**

## System:
 - OS: macOS 11.4
 - CPU: (12) x64 Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz
 - Memory: 10.25 GB / 64.00 GB
 - Shell: 5.8 - /bin/zsh
## Binaries:
 - Node: 14.17.0 - /usr/local/bin/node
 - npm: 7.19.1 - /usr/local/bin/npm
## Browsers:
 - Chrome: 92.0.4515.107
 - Edge: Not Found
 - Firefox: Not Found
 - Safari: 14.1.1
## npmGlobalPackages:
 - frontity: Not Found
 - npx: Not Found

**Possible solution**

I could see `https://favicon.frontity.org/` is deployed on Vercel, there are four solutions:

1. Change the site provider which is accessible in China.
2. Provide an option in CLI to skip the favicon downloading.
3. Make the inner request module use `http_proxy` and `https_proxy` like `curl` does.
4. Directly put favicon.ico in the git.

### PR DESCRIPTION
**Pull request by cbravobernal**
**What**:

Add a noFavicon option on `npx frontity create`

**Why**:

Right now, Frontity downloads the favicon from a Vercel server. In some places maybe there is no connection to Vercel, so people can't install Frontity. Fixes #861 

**How**:

Added an option to skip the favicon download.

**Tasks**:

- [x] Code
- [x] TSDocs
- [x] TypeScript
- [x] CLI E2E test
- [x] Add a changeset (with link to its [Feature Discussion](https://community.frontity.org/c/33) if it exists)

**Unrelated Tasks**

- [x] Unit tests
- [ ] TypeScript tests
- [ ] Update community discussions

**Additional Comments**

This is still a work in progress. Still needs testing. I don't know if this could be tested without creating a NPM package, or if would be better to do the save favicon in the repository and move it to the installation path, so we don't depend on Vercel for creating a project.

### CODE REVIEW

**Comment by luisherranz** [comment]
Hey @c4rl0sbr4v0 thanks for the PR 🙂

The code looks great to me!

Could you please add a CLI E2E test? You can use something similar to [this](https://github.com/frontity/frontity/blob/dev/packages/frontity/cli-e2e/filesystem/create.test.ts#L6-L27), but checking that the `favicon.ico` is not present.

And could you add a changeset as well? Thanks!!

_By the way, some tests have failed because this is an external fork, but the rest seems fine._  

PS: Please mark this PR as ready once it's finished and choose me as the reviewer.

**Comment by Ecostack** [comment]
Is there a way to use this commit version for `npx frontity`? Would be quite nice for certain regions!

**Comment by cbravobernal** [comment]
We still have an e2e failing `it("should not download favicon if option is given"`.
The snapshot is still giving favicon.ico file. So I cannot be really sure if this code will work on production.

Is there any way to run the cli on local? @michalczaplinski  @luisherranz  @DAreRodz

**Comment by luisherranz** [comment]
> Is there any way to run the cli on local?

Sure: https://github.com/frontity/frontity/tree/dev/packages/frontity/cli-e2e

**Comment by luisherranz** [comment]
@c4rl0sbr4v0 any clue why the CLI tests are not passing?

**Comment by cbravobernal** [comment]
> @c4rl0sbr4v0 any clue why the CLI tests are not passing?

To be honest, I'm not really sure. But the command line is not working as expected on local also. I put the favicon option as true by default, and `--no-favicon` will set the variable `favicon` to false. 

That case it should not create the favicon. But, when we do the tests, favicon file is there. I will try to take a look to the fix this week.

**Comment by luisherranz** [comment]
Why don't you propagate `noFavicon` internally instead of `favicon` like Eduardo did with `noGit`?

**Comment by luisherranz** [comment]
Superseded by https://github.com/frontity/frontity/pull/893

**Pull request closed without merging**
